withSlots: refactor out redundant React.Children traversal
microsoft/fluentui pull request #15462
Opened 2020-10-11 17:36 UTC by KevinTCoughlin

Visible while profiling `<Stack />`. Avoid traversing React.Children twice for children count, re-use `toArray`'s traversal.

![image](https://user-images.githubusercontent.com/706967/95685525-48967600-0bad-11eb-910b-069955a61e65.png)

Ideally this wrapper could re-use children already being traversed within `<Stack /> itself.

![image](https://user-images.githubusercontent.com/706967/95685550-6532ae00-0bad-11eb-9591-6a8af50b039f.png)

2020-10-11 21:19 UTC, Ridvanovskyy commented on packages/foundation/src/slots.tsx
>    if (slotType.isSlot) {
Hello, @KevinTCoughlin. I have small questions:
1. Can we take out `children = React.Children.toArray (children);` outside of check `if (slotType.isSlot) {}`? As I see this array is needed both `if` and for `else`.
2.  After we can add - **const** children = React.Children.toArray(children);

2020-10-11 21:41 UTC, Ridvanovskyy approved these changes

2020-10-12 00:02 UTC, khmakoto approved these changes

2020-10-12 00:07 UTC, khmakoto commented
Let's wait until version 8 beta release to merge this. Alternatively, we can merge into the 7.0 branch and port into 8.0 later. See #15222 for more details.

2020-10-12 00:08 UTC, khmakoto requested changes
Let's wait until version 8 beta release to merge this. Alternatively, we can merge into the 7.0 branch and port into 8.0 later. See #15222 for more details. Otherwise this LGTM.

2020-10-12 15:23 UTC, KevinTCoughlin commented
> Let's wait until version 8 beta release to merge this. Alternatively, we can merge into the 7.0 branch and port into 8.0 later. See #15222 for more details. Otherwise this LGTM.

@khmakoto here is the `7.0` cherry-pick, https://github.com/microsoft/fluentui/pull/15471. Can you ensure that is merged so OneDrive & SharePoint benefit soonest. Also please merge this change into `master` once the branch is stable so the perf fix is not lost. Thanks 🙇‍♂️.

2020-10-12 19:49 UTC, cliffkoh approved these changes

2020-10-13 16:54 UTC, xugao approved these changes
This is very interesting/good finding, thank you Kevin!

I see the gain in flamgrill tests as well:
![image](https://user-images.githubusercontent.com/1207059/95891485-fafb4400-0d39-11eb-84df-9b003e7692b0.png)

As you pointed out, the `React.children.toArray` call has significant cost as well

2020-10-20 00:30 UTC, khmakoto approved these changes

2020-10-20 00:30 UTC, merged