[UPP] Fix color contrast in UPP suggestion item close button
microsoft/fluentui pull request #16196
Opened 2020-12-09 23:44 UTC by salaman

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Replace neutralTertiaryAlt with neutralLight to fix a contrast issue with the remove button's hover state.

Before:
![image](https://user-images.githubusercontent.com/654562/101702179-39a93400-3a35-11eb-9920-15a4ef505576.png)

After:
![image](https://user-images.githubusercontent.com/654562/101702232-534a7b80-3a35-11eb-8a93-0fdc2147a270.png)

2020-12-09 23:56 UTC, elisabethcvs requested changes
Check HC mode as well to make sure that's in a good state too?

2020-12-10 00:14 UTC, fabricteam commented
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Avatar-mount_base.html">853</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Avatar-mount.html">835</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/BaseButtonCompat-mount_base.html">946</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/BaseButtonCompat-mount.html">965</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Breadcrumb-mount_base.html">41973</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Breadcrumb-mount.html">42611</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Checkbox-mount_base.html">1600</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Checkbox-mount.html">1590</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/CheckboxBase-mount_base.html">1321</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/CheckboxBase-mount.html">1330</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/ChoiceGroup-mount_base.html">4937</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/ChoiceGroup-mount.html">4956</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/ComboBox-mount_base.html">986</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/ComboBox-mount.html">1019</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/CommandBar-mount_base.html">10043</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/CommandBar-mount.html">10090</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/ContextualMenu-mount_base.html">6243</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/ContextualMenu-mount.html">6114</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButtonCompat</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DefaultButtonCompat-mount_base.html">1159</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DefaultButtonCompat-mount.html">1169</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DetailsRow-mount_base.html">3756</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DetailsRow-mount.html">3701</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DetailsRowFast-mount_base.html">3742</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DetailsRowFast-mount.html">3812</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DetailsRowNoStyles-mount_base.html">3541</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DetailsRowNoStyles-mount.html">3573</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Dialog-mount_base.html">1506</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Dialog-mount.html">1505</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DocumentCardTitle-mount_base.html">1821</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/DocumentCardTitle-mount.html">1767</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Dropdown-mount_base.html">3422</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/Dropdown-mount.html">3458</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/FocusTrapZone-mount_base.html">1819</a></td>
            <td><a href="http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/16196/merge/perf-test/FocusTrapZone-mount.html">1824</a></td>
    [...]

2020-12-10 18:33 UTC, salaman commented
> Check HC mode as well to make sure that's in a good state too?

@elisabethcvs HC was _okay_ but I pushed a change to make it more in-line with buttons and what it was in the old picker:

![image](https://user-images.githubusercontent.com/654562/101814339-dc63c000-3ad2-11eb-8311-89c426e13199.png)

2020-12-10 18:37 UTC, elisabethcvs approved these changes

2020-12-10 19:31 UTC, salaman commented
@elisabethcvs I cannot merge this so feel free to push the button.

2020-12-10 19:32 UTC, merged