Accessibility fix for single select dropdowns with NVDA in Browse or Forms mode
microsoft/fluentui pull request #17603
Opened 2021-03-27 17:53 UTC by vaishnavipulluri

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #16504 
- [x] Include a change request file using `$ yarn change`

#### Description of changes

role="listbox" on dropdown div (sibling element to label) is causing accessibility issues in NVDA Browse or Forms mode. User is unable to expand the single select dropdown.
role="button" on dropdown div can solve this issue with single select dropdowns and can provide better experience like multi-select dropdowns.
As we already have, role="listbox" and role="option" added over focusZone and child elements this will help screen reader in giving good information to the users as per my understanding..

#### Focus areas to test

Accessibility checks on single select and multi select dropdowns to make sure nothing is breaking.

2021-03-27 18:30 UTC, fabricteam commented
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Avatar-mount_base.html">1030</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Avatar-mount.html">1018</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/BaseButton-mount_base.html">1031</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/BaseButton-mount.html">1004</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Breadcrumb-mount_base.html">43872</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Breadcrumb-mount.html">44043</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/ButtonNext-mount_base.html">574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/ButtonNext-mount.html">572</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Checkbox-mount_base.html">1724</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Checkbox-mount.html">1675</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/CheckboxBase-mount_base.html">1390</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/CheckboxBase-mount.html">1366</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/ChoiceGroup-mount_base.html">5209</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/ChoiceGroup-mount.html">5068</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/ComboBox-mount_base.html">1054</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/ComboBox-mount.html">1039</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/CommandBar-mount_base.html">10328</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/CommandBar-mount.html">10542</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/ContextualMenu-mount_base.html">6444</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/ContextualMenu-mount.html">6489</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DefaultButton-mount_base.html">1198</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DefaultButton-mount.html">1192</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DetailsRow-mount_base.html">3779</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DetailsRow-mount.html">3807</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DetailsRowFast-mount_base.html">3854</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DetailsRowFast-mount.html">3778</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DetailsRowNoStyles-mount_base.html">3847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DetailsRowNoStyles-mount.html">3538</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Dialog-mount_base.html">1573</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Dialog-mount.html">1550</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DocumentCardTitle-mount_base.html">1905</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/DocumentCardTitle-mount.html">1837</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Dropdown-mount_base.html">3507</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/Dropdown-mount.html">3746</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/FocusTrapZone-mount_base.html">1855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/FocusTrapZone-mount.html">1863</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/FocusZone-mount_base.html">1831</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17603/perf-test/FocusZone-mount.html">1869</a></td>
            <td>5000</td>
            <td></t [...]

2021-03-30 19:01 UTC, smhigley requested changes
Thanks so much for submitting this PR! I've had my eye on updating the roles for this component, and I love that you jumped on it 😊.

I left a few suggestions, but the essentially amount to updating the pattern to be a combobox, rather than button/listbox. I know the latter is also in the ARIA Authoring practices for legacy reasons, so I get why you or anyone else would use it. Luckily, it's getting removed from the APG soon 😄.

2021-04-02 16:49 UTC, vaishnavipulluri commented
Updated Changes as suggested. Please review.

2021-04-02 16:51 UTC, vaishnavipulluri commented on packages/react/src/components/Dropdown/Dropdown.base.tsx
> +          role={'button'}
This is a great suggestion. Thanks for enhancing the fix.

2021-04-02 17:33 UTC, smhigley approved these changes
That looks good! Thanks again for the PR 😊

2021-04-05 19:11 UTC, joschect approved these changes

2021-04-06 16:24 UTC, merged