Recipient pill initials
microsoft/fluentui pull request #17716
Opened 2021-04-06 19:13 UTC by jaredi

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Account for email addresses between angled brackets in the display name. Do not want to use the email address to calculate the Display Name initials.

#### Focus areas to test

Display names with email addresses between () and {} and [] and <>, and display names without email addresses in the display name itself.

2021-04-06 19:47 UTC, fabricteam commented
## [Perf Analysis](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Avatar-mount_base.html">966</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Avatar-mount.html">973</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/BaseButton-mount_base.html">935</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/BaseButton-mount.html">930</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Breadcrumb-mount_base.html">42452</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Breadcrumb-mount.html">42515</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/ButtonNext-mount_base.html">571</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/ButtonNext-mount.html">575</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Checkbox-mount_base.html">1676</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Checkbox-mount.html">1600</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/CheckboxBase-mount_base.html">1395</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/CheckboxBase-mount.html">1422</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/ChoiceGroup-mount_base.html">4977</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/ChoiceGroup-mount.html">5013</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/ComboBox-mount_base.html">1016</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/ComboBox-mount.html">1004</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/CommandBar-mount_base.html">9979</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/CommandBar-mount.html">10066</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/ContextualMenu-mount_base.html">6146</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/ContextualMenu-mount.html">6384</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DefaultButton-mount_base.html">1157</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DefaultButton-mount.html">1185</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DetailsRow-mount_base.html">3741</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DetailsRow-mount.html">3883</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DetailsRowFast-mount_base.html">3852</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DetailsRowFast-mount.html">3771</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DetailsRowNoStyles-mount_base.html">3509</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DetailsRowNoStyles-mount.html">3552</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Dialog-mount_base.html">1485</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Dialog-mount.html">1482</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DocumentCardTitle-mount_base.html">1806</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/DocumentCardTitle-mount.html">1779</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Dropdown-mount_base.html">3321</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/Dropdown-mount.html">3312</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/FocusTrapZone-mount_base.html">1847</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/FocusTrapZone-mount.html">1799</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/FocusZone-mount_base.html">1731</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/17716/perf-test/FocusZone-mount.html">1704</a></td>
            <td>5000</td>
            <td></td>
   [...]

2021-04-06 20:39 UTC, elisabethcvs requested changes
I think you should probably add tests to initials.test.ts and Persona.test.tsx.

I also added mtennoe as he reviewed my previous change in this file

2021-04-07 08:20 UTC, mtennoe commented on packages/utilities/src/initials.ts
> +const UNWANTED_ENCLOSURES_REGEX: RegExp = /[\(\[\{\<][^\)\]\}\>]*[\)\]\}\>]/g;
Agree with @elisabethcvs - Lets add tests and examples for this

2021-04-07 22:25 UTC, elisabethcvs commented on packages/react-examples/src/react-experiments/Persona/Persona.Example.tsx
>              <Stack tokens={tokens.personaCoinStack}>
there's a version of this in the main react directory, that should be updated as well (and I think there are snapshot tests for that one)

2021-04-08 20:18 UTC, elisabethcvs approved these changes

2021-04-12 09:30 UTC, mtennoe approved these changes

2021-04-12 09:30 UTC, merged