feat: add web components toolbar
microsoft/fluentui pull request #19155
Opened 2021-07-27 19:30 UTC by SethDonohue

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes
Adds the Toolbar Component

<img width="922" alt="Screen Shot 2021-07-27 at 12 29 22 PM" src="https://user-images.githubusercontent.com/31681651/127216101-38ef033f-1361-4262-8c9e-a8e61d057556.png">
<img width="984" alt="Screen Shot 2021-07-27 at 12 30 03 PM" src="https://user-images.githubusercontent.com/31681651/127216106-0597e43d-cc19-4d4e-817a-c875b6ffc096.png">

2021-07-27 19:33 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/ce2c432e3da011d696c71329e49ffba39997ddf9'>ce2c432e3da011d696c71329e49ffba39997ddf9</a></sub>
<div id="bundleSizeComment9423"/>

2021-07-27 19:41 UTC, EisenbergEffect approved these changes

2021-07-27 19:48 UTC, SethDonohue commented
I'm going to update the styling a touch, it's height is a bit off.

2021-07-27 20:02 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Avatar-mount_base.html">877</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Avatar-mount.html">886</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/BaseButton-mount_base.html">974</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/BaseButton-mount.html">1045</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Breadcrumb-mount_base.html">2729</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Breadcrumb-mount.html">2785</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/ButtonNext-mount_base.html">457</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/ButtonNext-mount.html">475</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Checkbox-mount_base.html">1703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Checkbox-mount.html">1636</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/CheckboxBase-mount_base.html">1408</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/CheckboxBase-mount.html">1460</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/ChoiceGroup-mount_base.html">5133</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/ChoiceGroup-mount.html">5103</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/ComboBox-mount_base.html">1080</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/ComboBox-mount.html">980</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/CommandBar-mount_base.html">10571</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/CommandBar-mount.html">10380</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/ContextualMenu-mount_base.html">6550</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/ContextualMenu-mount.html">6537</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DefaultButton-mount_base.html">1279</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DefaultButton-mount.html">1280</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DetailsRow-mount_base.html">4265</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DetailsRow-mount.html">4123</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DetailsRowFast-mount_base.html">3978</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DetailsRowFast-mount.html">3902</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DetailsRowNoStyles-mount_base.html">3803</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DetailsRowNoStyles-mount.html">3832</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Dialog-mount_base.html">2247</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Dialog-mount.html">2302</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DocumentCardTitle-mount_base.html">143</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/DocumentCardTitle-mount.html">142</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Dropdown-mount_base.html">3506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/Dropdown-mount.html">3546</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/FluentProviderNext-mount_base.html">7348</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/FluentProviderNext-mount.html">7415</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/FocusTrapZone-mount_base.html">1909</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19155/perf-test/FocusTrapZone-mount.html">1868</a></td>
       [...]

2021-08-04 17:56 UTC, scomea approved these changes

2021-09-13 17:51 UTC, khamudom approved these changes

2021-09-14 17:01 UTC, chrisdholt commented on change/@fluentui-web-components-befdf28c-0bd2-48cc-8075-55b3684202e2.json
> +  "comment": "add toolbar",
```suggestion
add toolbar as a new web component
```

2021-09-14 17:19 UTC, SethDonohue commented on change/@fluentui-web-components-befdf28c-0bd2-48cc-8075-55b3684202e2.json
> +  "comment": "add toolbar",
updated

2021-09-14 17:34 UTC, chrisdholt requested changes
Looks like there are some unrelated changes in this PR with the latest update. I don't think we want to include the removed changed files here - that seems odd

2021-09-14 18:35 UTC, ecraig12345 approved these changes
Approved for yarn.lock changes

2021-09-14 18:49 UTC, chrisdholt approved these changes

2021-09-14 18:50 UTC, merged