Fix: DocumentCardPreview layout when text spacing increased
microsoft/fluentui pull request #19584
Opened 2021-08-31 20:01 UTC by GeoffCoxMSFT

#### Pull request checklist

- [X] Addresses an existing issue: Fixes https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/12755
- [X] Include a change request file using `$ yarn change`

#### Description of changes

When the text spacing was increased, the list items in the DocumentCardPreview would overlap and be partially hidden because the height was fixed.
- I updated the list item style to remove the 16px hard-coded height in favor of a flexbox layout.  
- The icon and text are vertically centered.
- The list item elements won't wrap as the text will ellipse truncate as width decreases.
- The icon is auto sized and won't shrink when the text tries to expand.
- The text (link) will grow to the remainder of the space.

#### Focus areas to test

Unresolved secondary issue:  The DocumentCardPreview has a 16px padding around the list.  This is consistent with the padding around the card contents.  However, in compact mode with text spacing increased, the '+3 more' overflow text of the preview gets cut off.  The problem is that the preview doesn't know the parent card is in compact mode and so doesn't have any logic to reduce the padding from 16px to something like 8px.  I didn't want to introduce a new property to the preview type nor make the preview padding inconsistent.

#### Before & After
(Note: Font sizes didn't change, the before is from the Fluent UI home page and the after is from my local storybook)

Before - Normal
<img width="257" alt="documentcardpreview_normal_before" src="https://user-images.githubusercontent.com/28762486/131568020-a25a9a0f-223d-4eb5-ae89-099f01f19e3e.png">

Before - Expanded Text Spacing
<img width="257" alt="documentcardpreview_textspacing_before" src="https://user-images.githubusercontent.com/28762486/131568056-58b1ca60-47f1-4b0f-9fbc-f95aedeecd7a.png">

After - Normal
<img width="265" alt="documentcardpreview_normal_after" src="https://user-images.githubusercontent.com/28762486/131568143-4dced99f-a0c5-4ea2-9d42-17f70bdc4932.png">

After - Expanded Text Spacing
<img width="263" alt="documentcardpreview_textspacing_after" src="https://user-images.githubusercontent.com/28762486/131568154-fe9f28a2-c03d-48bb-bdd5-221dea501d8e.png">

2021-08-31 20:04 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/035927b72db8e4ca87ed307bd1a3e7fc2c0e00dc'>035927b72db8e4ca87ed307bd1a3e7fc2c0e00dc</a></sub>
<div id="bundleSizeComment9423"/>

2021-08-31 20:28 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Avatar-mount_base.html">867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Avatar-mount.html">885</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/BaseButton-mount_base.html">885</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/BaseButton-mount.html">854</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Breadcrumb-mount_base.html">2598</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Breadcrumb-mount.html">2619</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/ButtonNext-mount_base.html">415</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/ButtonNext-mount.html">432</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Checkbox-mount_base.html">1494</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Checkbox-mount.html">1446</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/CheckboxBase-mount_base.html">1294</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/CheckboxBase-mount.html">1312</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/ChoiceGroup-mount_base.html">4572</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/ChoiceGroup-mount.html">4708</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/ComboBox-mount_base.html">1003</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/ComboBox-mount.html">934</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/CommandBar-mount_base.html">10122</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/CommandBar-mount.html">9986</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/ContextualMenu-mount_base.html">6177</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/ContextualMenu-mount.html">6203</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DefaultButton-mount_base.html">1096</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DefaultButton-mount.html">1077</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DetailsRow-mount_base.html">3704</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DetailsRow-mount.html">3634</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DetailsRowFast-mount_base.html">3660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DetailsRowFast-mount.html">3645</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DetailsRowNoStyles-mount_base.html">3466</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DetailsRowNoStyles-mount.html">3409</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Dialog-mount_base.html">2069</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Dialog-mount.html">2060</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DocumentCardTitle-mount_base.html">140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/DocumentCardTitle-mount.html">131</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Dropdown-mount_base.html">3216</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/Dropdown-mount.html">3176</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/FluentProviderNext-mount_base.html">7380</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/FluentProviderNext-mount.html">7195</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/FocusTrapZone-mount_base.html">1762</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19584/perf-test/FocusTrapZone-mount.html">1780</a></td>
         [...]

2021-09-01 00:34 UTC, smhigley requested changes
I think it's a good change! It does look like there are some other rogue pixel height declarations in other DocumentCard styles that are clipping text after text spacing is applied:
- line 24 in DocumentCardActions.styles.ts
- line 68 in DocumentCard.styles.ts
- line 23 in DocumentCardTitle.styles.ts

2021-09-01 17:37 UTC, GeoffCoxMSFT commented
> I think it's a good change! It does look like there are some other rogue pixel height declarations in other DocumentCard styles that are clipping text after text spacing is applied:
> 
> * line 24 in DocumentCardActions.styles.ts
> * line 68 in DocumentCard.styles.ts
> * line 23 in DocumentCardTitle.styles.ts

OK.  I will try to fix those with this PR. I'm concerned that it might cause the card to expand larger than it should when in compact mode, but that is probably better than clipping content.

2021-09-02 22:59 UTC, smhigley approved these changes
🎉

2021-09-03 21:39 UTC, merged