Added disabled state for React/DetailsRow
microsoft/fluentui pull request #19979
Opened 2021-09-25 02:21 UTC by shravva

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

2021-09-25 02:32 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/206633ac9eadc223e3ce6cf0afcaf4a1595aa383'>206633ac9eadc223e3ce6cf0afcaf4a1595aa383</a></sub>
<div id="bundleSizeComment9423"/>

2021-09-25 03:34 UTC, ThomasMichon approved these changes

2021-09-27 18:59 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Avatar-mount_base.html">1028</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Avatar-mount.html">1043</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/BaseButton-mount_base.html">1013</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/BaseButton-mount.html">1028</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Breadcrumb-mount_base.html">2763</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Breadcrumb-mount.html">2756</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/ButtonNext-mount_base.html">504</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/ButtonNext-mount.html">506</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Checkbox-mount_base.html">1706</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Checkbox-mount.html">1709</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/CheckboxBase-mount_base.html">1510</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/CheckboxBase-mount.html">1497</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/ChoiceGroup-mount_base.html">5269</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/ChoiceGroup-mount.html">5276</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/ComboBox-mount_base.html">1041</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/ComboBox-mount.html">1059</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/CommandBar-mount_base.html">10866</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/CommandBar-mount.html">10847</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/ContextualMenu-mount_base.html">6898</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/ContextualMenu-mount.html">7019</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DefaultButton-mount_base.html">1265</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DefaultButton-mount.html">1294</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DetailsRow-mount_base.html">4009</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DetailsRow-mount.html">4171</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DetailsRowFast-mount_base.html">4061</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DetailsRowFast-mount.html">4130</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DetailsRowNoStyles-mount_base.html">3824</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DetailsRowNoStyles-mount.html">3998</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Dialog-mount_base.html">2542</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Dialog-mount.html">2540</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DocumentCardTitle-mount_base.html">177</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/DocumentCardTitle-mount.html">177</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Dropdown-mount_base.html">3530</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/Dropdown-mount.html">3572</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/FluentProviderNext-mount_base.html">7384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/FluentProviderNext-mount.html">7448</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/FluentProviderWithTheme-mount_base.html">355</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/19979/perf-test/FluentProviderWithTheme [...]

2021-09-28 21:10 UTC, smhigley requested changes
I was actually pleasantly surprised at how well this works in screen readers. The `aria-disabled` state was read for the row on focus, and also for inner cells in virtual cursor (where applicable) in all the following combos I tested:
- Narrator + Edge
- NVDA + Firefox and Chrome
- JAWS + Chrome
- VoiceOver + Safari on iOS and macOS
- Talkback + Chrome on Android

There are two things I think it would be good to include in this PR:
1. Propagate the disabled state to the DetailsRowCheck, so that can also be styled
2. Prevent selection changes on disabled rows

Thanks for the contribution!

2021-09-30 21:55 UTC, ThomasMichon commented on packages/react/src/components/DetailsList/DetailsRow.base.tsx
> +        aria-disabled={disabled}
```ts
aria-disabled={disabled || undefined}
data-selection-disabled={disabled || undefined}
```

2021-09-30 23:37 UTC, shravva commented on packages/react/src/components/DetailsList/DetailsRow.base.tsx
> +        aria-disabled={disabled}
updated

2021-10-01 19:34 UTC, ThomasMichon approved these changes

2021-10-01 20:47 UTC, smhigley approved these changes

2021-10-01 20:47 UTC, merged

2021-11-03 22:36 UTC, mltejera commented
Hi Folks - looks like a breaking change snuck into this one. 'disabled' is now required on IDetailsRowStyleProps, which broke our stuff. It's also been cherry-picked to v7, breaking that branch too.

2021-11-04 03:01 UTC, ecraig12345 commented
@mltejera Sorry about that! @khmakoto made PRs fixing it in both branches, and the fixes should be released overnight.

2021-11-04 20:52 UTC, mltejera commented
@ecraig12345 thanks again so much for the fast turnaround 🙏 You guys rock!