make teamsV2Theme the default docs theme
microsoft/fluentui pull request #20442
Opened 2021-11-02 00:16 UTC by davezuko

As I understand it, teamsTheme is deprecated in favor of teamsV2Theme. I've received some requests to change the documentation website's default theme to the most current version, for example to help designers who are visiting the color scheme/palette pages and don't realize that they're looking at the old set of colors.

2021-11-02 00:33 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/42315bf9bdc7810cd0fba0cc77ecb975d95ea86e'>42315bf9bdc7810cd0fba0cc77ecb975d95ea86e</a></sub>
<div id="bundleSizeComment9423"/>

2021-11-02 00:49 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Avatar-mount_base.html">976</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Avatar-mount.html">926</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/BaseButton-mount_base.html">931</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/BaseButton-mount.html">965</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Breadcrumb-mount_base.html">2751</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Breadcrumb-mount.html">2794</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/ButtonNext-mount_base.html">541</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/ButtonNext-mount.html">517</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Checkbox-mount_base.html">1595</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Checkbox-mount.html">1594</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/CheckboxBase-mount_base.html">1359</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/CheckboxBase-mount.html">1351</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/ChoiceGroup-mount_base.html">4878</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/ChoiceGroup-mount.html">4870</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/ComboBox-mount_base.html">1018</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/ComboBox-mount.html">1014</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/CommandBar-mount_base.html">10615</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/CommandBar-mount.html">10846</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/ContextualMenu-mount_base.html">6736</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/ContextualMenu-mount.html">6667</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DefaultButton-mount_base.html">1165</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DefaultButton-mount.html">1141</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DetailsRow-mount_base.html">3912</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DetailsRow-mount.html">3875</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DetailsRowFast-mount_base.html">3954</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DetailsRowFast-mount.html">3864</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DetailsRowNoStyles-mount_base.html">3757</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DetailsRowNoStyles-mount.html">3785</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Dialog-mount_base.html">2696</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Dialog-mount.html">2692</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DocumentCardTitle-mount_base.html">160</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/DocumentCardTitle-mount.html">162</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Dropdown-mount_base.html">3324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/Dropdown-mount.html">3292</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/FluentProviderNext-mount_base.html">3522</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/FluentProviderNext-mount.html">3495</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/FluentProviderWithTheme-mount_base.html">220</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/20442/perf-test/FluentProviderWithTheme-mou [...]

2021-11-02 18:32 UTC, jurokapsiar requested changes
This has implications on testing and integration, I will reach out to you to clarify next steps.

2021-11-03 20:54 UTC, davezuko commented
@jurokapsiar, I've added a simple workaround to make the v1 theme the default during screener tests. All of those tests are passing now.

2021-11-04 16:50 UTC, jurokapsiar commented
> @jurokapsiar, I've added a simple workaround to make the v1 theme the default during screener tests. All of those tests are passing now.

Created #20501 to clean it up once the theme merging gets simplified and we fully deprecate v1 theme.

2021-11-04 16:51 UTC, jurokapsiar approved these changes

2021-11-04 16:57 UTC, merged