fixed icon search field
microsoft/fluentui pull request #21250
Opened 2022-01-11 22:42 UTC by micahgodbolt

fixed website bug where page errors out when clear is hit on icon search

https://developer.microsoft.com/en-us/fluentui#/styles/web/icons

2022-01-11 22:55 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/06cb25c66838875a18dc264ebfa8c5547ce4ebb2'>06cb25c66838875a18dc264ebfa8c5547ce4ebb2</a></sub>
<div id="bundleSizeComment9423"/>

2022-01-11 23:19 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Avatar-mount_base.html">976</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Avatar-mount.html">987</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/BaseButton-mount_base.html">1026</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/BaseButton-mount.html">1015</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Breadcrumb-mount_base.html">2648</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Breadcrumb-mount.html">2657</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/ButtonNext-mount_base.html">583</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/ButtonNext-mount.html">557</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Checkbox-mount_base.html">1634</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Checkbox-mount.html">1660</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/CheckboxBase-mount_base.html">1418</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/CheckboxBase-mount.html">1408</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/ChoiceGroup-mount_base.html">5072</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/ChoiceGroup-mount.html">5034</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/ComboBox-mount_base.html">1075</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/ComboBox-mount.html">1002</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/CommandBar-mount_base.html">10215</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/CommandBar-mount.html">10184</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/ContextualMenu-mount_base.html">8379</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/ContextualMenu-mount.html">8475</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DefaultButton-mount_base.html">1197</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DefaultButton-mount.html">1218</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DetailsRow-mount_base.html">3908</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DetailsRow-mount.html">3939</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DetailsRowFast-mount_base.html">3952</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DetailsRowFast-mount.html">3977</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DetailsRowNoStyles-mount_base.html">3806</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DetailsRowNoStyles-mount.html">3716</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Dialog-mount_base.html">2670</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Dialog-mount.html">2727</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DocumentCardTitle-mount_base.html">198</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/DocumentCardTitle-mount.html">204</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Dropdown-mount_base.html">3370</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/Dropdown-mount.html">3337</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/FluentProviderNext-mount_base.html">1767</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/FluentProviderNext-mount.html">1793</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/FluentProviderWithTheme-mount_base.html">163</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21250/perf-test/FluentProviderWithTheme-m [...]

2022-01-12 00:19 UTC, spmonahan approved these changes

2022-01-12 00:47 UTC, micahgodbolt commented
Blah, some unrelated screener error.

2022-01-12 21:02 UTC, ecraig12345 requested changes
Let's go with the fix of the root cause instead: #21268

2022-01-12 22:29 UTC, closed without merging