positioningContainer to include changes in v8
microsoft/fluentui pull request #21375
Opened 2022-01-21 21:00 UTC by sbarrameda

## Current Behavior

Target moves on scroll; if coachmark is in dialog, and dialog body string is too long, the target of the coachmark moves
## New Behavior
behavior in v8. target does not move. coachmark positions to correct target

## Related Issue(s)

Fixes #

2022-01-21 21:01 UTC, sbarrameda commented
I ported changes from v8 Coachmark/PositioningContainer to this version

2022-01-25 00:11 UTC, ecraig12345 requested changes
Thanks for the contribution, but all the changes to use `import type` syntax need to be reverted to avoid causing compatibility issues for consumers of v8. (This syntax was only added in typescript 3.8, and our consumer min bar for v7 is 3.5.)

2022-01-25 00:11 UTC, ecraig12345 commented on packages/office-ui-fabric-react/src/components/Coachmark/PositioningContainer/PositioningContainer.styles.ts
> +import type { IStyle } from '../../../Styling';
This one needs to be reverted--v7 doesn't support type imports
```suggestion
import { mergeStyleSets, focusClear, IStyle, HighContrastSelector } from '../../../Styling';
```

2022-01-25 00:11 UTC, ecraig12345 commented on packages/office-ui-fabric-react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx
> +import type { IPositioningContainerProps } from './PositioningContainer.types';
These `import type` changes also need to be reverted. (Same in all other files.)

2022-02-16 19:00 UTC, closed without merging