DocumentCard: parent container is no longer focusable and now has role=group to improve a11y experience
microsoft/fluentui pull request #21461
Opened 2022-01-26 20:49 UTC by TristanWatanabe

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #17718
- [x] Include a change request file using `$ yarn change`

#### Description of changes

- `DocumentCard` now has `tabIndex` removed and now has static `role="group"` so it's no longer focusable.
-  Focus now moves to `DocumentCardTitle`.
- `DocumentCard` now passes props `role` and `tabIndex` to `DocumentCardTitle` via helper function `passPropsToTitle`.
	- `passPropsToTitle` recursively goes through all children to find the `DocumentCardTitle` element and passes the props `role` and `tabIndex` to it.
	- This was done in order to provide the new behavior without having consumers modify how they currently use the component.

- Redo of #17806

2022-01-26 21:05 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/05da13bb294d7152dc8bb4e5a5fdc72d502156d3'>05da13bb294d7152dc8bb4e5a5fdc72d502156d3</a></sub>
<div id="bundleSizeComment9423"/>

2022-01-26 21:16 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Avatar-mount_base.html">803</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Avatar-mount.html">808</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/BaseButton-mount_base.html">768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/BaseButton-mount.html">817</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Breadcrumb-mount_base.html">2099</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Breadcrumb-mount.html">2282</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ButtonNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/ButtonNext-mount_base.html">437</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/ButtonNext-mount.html">422</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Checkbox-mount_base.html">1263</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Checkbox-mount.html">1358</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/CheckboxBase-mount_base.html">1140</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/CheckboxBase-mount.html">1142</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/ChoiceGroup-mount_base.html">3783</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/ChoiceGroup-mount.html">4041</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/ComboBox-mount_base.html">908</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/ComboBox-mount.html">850</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/CommandBar-mount_base.html">8378</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/CommandBar-mount.html">8544</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/ContextualMenu-mount_base.html">15606</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/ContextualMenu-mount.html">14696</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DefaultButton-mount_base.html">991</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DefaultButton-mount.html">993</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DetailsRow-mount_base.html">3257</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DetailsRow-mount.html">3110</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DetailsRowFast-mount_base.html">3182</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DetailsRowFast-mount.html">3256</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DetailsRowNoStyles-mount_base.html">3022</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DetailsRowNoStyles-mount.html">3011</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Dialog-mount_base.html">2248</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Dialog-mount.html">2258</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DocumentCardTitle-mount_base.html">151</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/DocumentCardTitle-mount.html">166</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Dropdown-mount_base.html">2747</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/Dropdown-mount.html">2563</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderNext</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/FluentProviderNext-mount_base.html">1492</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/FluentProviderNext-mount.html">1558</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/FluentProviderWithTheme-mount_base.html">125</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/21461/perf-test/FluentProviderWithTheme-mount.h [...]

2022-04-20 00:30 UTC, smhigley requested changes
Question on this -- the React.Children approach seems to depend on DocumentCardTitle being the only child that has a `title` prop, which is problematic since `title` is also an HTML prop.

So, for instance, this will cause unexpected consequences for the button:
```jsx
<DocumentCard
    aria-label="Default Document Card with large file name. Created by Annie Lindqvist a few minutes ago."
    onClickHref="http://bing.com"
  >
    <DocumentCardPreview {...previewProps} />
    <DocumentCardTitle title={'File_name.txt'} />
    <button title="tooltip text">Some action</button> 
    <DocumentCardActivity activity="Created a few minutes ago" people={DocumentCardActivityPeople} />
  </DocumentCard>
``` 

I think it'd probably be better to implement a context, and have DocumentCardTitle directly pull role/tabindex from it. Some v8 components already do this -- ResizeGroup, ScrollablePane, and ContextualMenu all look like they do, so it wouldn't be unprecedented.

2022-04-21 23:44 UTC, TristanWatanabe commented on packages/react/src/components/DocumentCard/DocumentCard.base.tsx
> +function passPropsToTitle(
Yup didn't account for that as a native prop - I have updated the implementation to use a react context instead in this commit 952c97d

2022-04-22 00:28 UTC, spmonahan approved these changes

2022-04-22 16:49 UTC, smhigley approved these changes
It looks like we'll also need `:focus-visible` styles for the title, but I'll approve this PR and open a separate issue

2022-04-22 16:50 UTC, merged