Reexport react-spinner in react-components
microsoft/fluentui pull request #22531
Opened 2022-04-18 14:14 UTC by tomi-msft

This PR is to reexport react-spinner into react-components unstable

2022-04-18 14:22 UTC, fabricteam commented
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `176.089 kB`<br />`49.113 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `32.601 kB`<br />`10.668 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |   `16.459 kB`<br />`5.549 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/ad9b7e67ee94a2115316efe3299a2ff3b678ec1b'>ad9b7e67ee94a2115316efe3299a2ff3b678ec1b</a></sub>
<div id="bundleSizeComment9423"/>

2022-04-20 21:20 UTC, sopranopillow approved these changes

2022-04-20 21:30 UTC, spmonahan requested changes
I think you should update the Storybook meta to 'Preview Components/Spinner` so the docs are put in the correct section of the Storybook docs.

https://github.com/microsoft/fluentui/blob/master/packages/react-spinner/src/stories/Spinner.stories.tsx#L12

2022-04-21 16:37 UTC, spmonahan approved these changes

2022-04-21 16:40 UTC, merged