feat(react-conformance): Add getPortalElement to static classnames object test
microsoft/fluentui pull request #23631
Opened 2022-06-21 20:00 UTC by sopranopillow

## Current Behavior

The `component-has-static-classnames-object` test, specifically the `has static classnames in rendered component` portion, doesn't handle internal portal elements. An example could be a popover that is only rendered when the trigger is clicked.

## New Behavior

The `has-static-classnames` options now have a `getPortalElement` to allow the user to find the element and check for the classnames inside the portal element.

## Related Issue(s)

#23549

2022-06-22 16:07 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/Avatar-mount_base.html">1701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/Avatar-mount.html">1671</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/Button-mount_base.html">1267</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/Button-mount.html">1241</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/FluentProvider-mount_base.html">2230</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/FluentProvider-mount.html">2274</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/FluentProviderWithTheme-mount_base.html">844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/FluentProviderWithTheme-mount.html">911</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">816</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">872</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">915</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">904</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/MakeStyles-mount_base.html">2450</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-react-components/MakeStyles-mount.html">2469</a></td>
            <td>50000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2022-06-22 16:14 UTC, fabricteam commented
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |  `75.346 kB`<br />`22.865 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `46.031 kB`<br />`13.438 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |   `20.929 kB`<br />`6.554 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `21.833 kB`<br />`6.861 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |   `22.627 kB`<br />`6.802 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `33.796 kB`<br />`9.151 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |  `40.703 kB`<br />`10.403 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |  `36.365 kB`<br />`10.033 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |    `43.6 kB`<br />`11.351 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `48.279 kB`<br />`10.573 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |   `66.137 kB`<br />`18.69 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `61.293 kB`<br />`17.567 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `7.737 kB`<br />`3.264 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |    `9.302 kB`<br />`3.779 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `7.838 kB`<br />`3.316 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox</abbr>                                                                              |  `61.189 kB`<br />`20.959 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `185.394 kB`<br />`51.302 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |   `31.16 kB`<br />`10.215 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `15.597 kB`<br />`5.539 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |    `9.956 kB`<br />`3.922 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |   `22.009 kB`<br />`7.194 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |    `8.514 kB`<br />`3.526 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |    `11.358 kB`<br />`4.58 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `114.086 kB`<br />`34.592 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `117.261 kB`<br />`35.067 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 |  `104.06 kB`<br />`31.651 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |    `9.317 kB`<br />`3.451 kB` |
| <samp>react-provider</samp> <br /> <abbr title='bundle-size/FluentProvider.fixture.js'>FluentProvider</abbr>                                                                  |   `14.037 kB`<br />`5.307 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/Radio.fixture.js'>Radio</abbr>                                                                                       |  `29.696 kB`<br />`10.117 kB` |
| <samp>react-radio</samp> <br /> <abbr title='bundle-size/RadioGroup.fixture.js'>RadioGroup</abbr>                                                                             |    `13.595 kB`<br />`5.42 kB` |
| <samp>react-select</samp> <br /> <abbr title='bundle-size/Select.fixture.js'>Select</abbr>                                                                                    |   `19.118 kB`<br />`6.841 kB` |
| <samp>react-slider</samp> <br /> <abbr title='bundle-size/Slider.fixture.js'>Slider</abbr>                                                                                    |   `25.124 kB`<br />`8.081 kB` |
| <samp>react-spinbutton</samp> <br /> <abbr title='bundle-size/SpinButton.fixture.js'>SpinButton</abbr>                                                                        |  `42.364 kB`<br />`11.944 kB` |
| <samp>react-spinner</samp> <br /> <abbr title='bundle-size/Spinner.fixture.js'>Spinner</abbr>                                                                                 |    `18.159 kB`<br />`5.99 kB` |
| <samp>react-switch</samp> <br /> <abbr title='bundle-size/Switch.fixture.js'>Switch</abbr>                                                                                    |   `25.658 kB`<br />`8.276 kB` |
| <samp>react-text</samp> <br /> <abbr title='bundle-size/Text.Default.fixture.js'>Text - Default</abbr>                                                     [...]

2022-06-22 16:16 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/BaseButton-mount_base.html">790</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/BaseButton-mount.html">790</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Breadcrumb-mount_base.html">2285</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Breadcrumb-mount.html">2215</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Checkbox-mount_base.html">1279</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Checkbox-mount.html">1257</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/CheckboxBase-mount_base.html">1083</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/CheckboxBase-mount.html">1083</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/ChoiceGroup-mount_base.html">3926</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/ChoiceGroup-mount.html">3897</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/ComboBox-mount_base.html">768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/ComboBox-mount.html">742</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/CommandBar-mount_base.html">8766</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/CommandBar-mount.html">8733</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/ContextualMenu-mount_base.html">9182</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/ContextualMenu-mount.html">9257</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DefaultButton-mount_base.html">955</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DefaultButton-mount.html">965</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DetailsRow-mount_base.html">3046</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DetailsRow-mount.html">3019</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DetailsRowFast-mount_base.html">3054</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DetailsRowFast-mount.html">3027</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DetailsRowNoStyles-mount_base.html">2884</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DetailsRowNoStyles-mount.html">2870</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Dialog-mount_base.html">2335</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Dialog-mount.html">2310</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DocumentCardTitle-mount_base.html">142</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/DocumentCardTitle-mount.html">149</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Dropdown-mount_base.html">2807</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Dropdown-mount.html">2803</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/FocusTrapZone-mount_base.html">1558</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/FocusTrapZone-mount.html">1593</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/FocusZone-mount_base.html">1520</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/FocusZone-mount.html">1506</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/IconButton-mount_base.html">1399</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/IconButton-mount.html">1390</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Label-mount_base.html">316</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test/Label-mount.html">318</a></td>
            <td>5000</td>
            <t [...]

2022-06-22 16:16 UTC, fabricteam commented
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
BoxMinimalPerf.default | [387](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/BoxMinimalPerf.default.html) | [333](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.16:1
HeaderSlotsPerf.default | [887](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/HeaderSlotsPerf.default.html) | [792](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.12:1
HeaderMinimalPerf.default | [408](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/HeaderMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.11:1
ChatWithPopoverPerf.default | [441](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ChatWithPopoverPerf.default.html) | [400](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.1:1
DialogMinimalPerf.default | [854](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/DialogMinimalPerf.default.html) | [783](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.09:1
FormMinimalPerf.default | [453](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/FormMinimalPerf.default.html) | [414](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.09:1
ProviderMergeThemesPerf.default | [1310](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [1197](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.09:1
TableManyItemsPerf.default | [2206](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TableManyItemsPerf.default.html) | [2036](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.08:1
ImageMinimalPerf.default | [409](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ImageMinimalPerf.default.html) | [382](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.07:1
AttachmentMinimalPerf.default | [188](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/AttachmentMinimalPerf.default.html) | [177](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.06:1
StatusMinimalPerf.default | [754](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/StatusMinimalPerf.default.html) | [709](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.06:1
TextMinimalPerf.default | [359](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TextMinimalPerf.default.html) | [340](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.06:1
TreeWith60ListItems.default | [173](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TreeWith60ListItems.default.html) | [163](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.06:1
ListMinimalPerf.default | [532](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ListMinimalPerf.default.html) | [508](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.05:1
MenuMinimalPerf.default | [914](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/MenuMinimalPerf.default.html) | [874](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.05:1
ReactionMinimalPerf.default | [392](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ReactionMinimalPerf.default.html) | [373](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.05:1
TextAreaMinimalPerf.default | [559](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TextAreaMinimalPerf.default.html) | [531](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.05:1
CustomToolbarPrototype.default | [2752](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/CustomToolbarPrototype.default.html) | [2618](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/CustomToolbarPrototype.default_base.html) | 1.05:1
ChatMinimalPerf.default | [840](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ChatMinimalPerf.default.html) | [806](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.04:1
InputMinimalPerf.default | [1354](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/InputMinimalPerf.default.html) | [1304](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.04:1
LayoutMinimalPerf.default | [381](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/LayoutMinimalPerf.default.html) | [367](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
RefMinimalPerf.default | [235](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/RefMinimalPerf.default.html) | [225](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.04:1
TableMinimalPerf.default | [414](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TableMinimalPerf.default.html) | [398](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.04:1
DropdownManyItemsPerf.default | [737](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/DropdownManyItemsPerf.default.html) | [717](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.03:1
GridMinimalPerf.default | [349](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/GridMinimalPerf.default.html) | [338](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.03:1
LoaderMinimalPerf.default | [700](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/LoaderMinimalPerf.default.html) | [689](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
SkeletonMinimalPerf.default | [359](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/SkeletonMinimalPerf.default.html) | [353](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1522](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1500](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.01:1
ChatDuplicateMessagesPerf.default | [315](https://fluentuipr.z22.web.core.windows.net/pull/23631/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [312](https://fluentuipr.z22.web.core.windows.net [...]

2022-06-23 15:45 UTC, spmonahan requested changes

2022-06-23 17:45 UTC, spmonahan requested changes

2022-06-23 17:45 UTC, spmonahan commented on packages/react-conformance/src/defaultTests.tsx
> +        if (missingClassNames && portalEl) {
```suggestion
        if (missingClassNames.length && portalEl) {
```

`missingClassNames` will always be truthy, we want to check `length` to know if there's anything potentially missing.

2022-06-23 19:34 UTC, spmonahan approved these changes

2022-06-23 19:39 UTC, merged