Make getKey and selection props mutually exclusive
microsoft/fluentui pull request #24048
Opened 2022-07-24 13:36 UTC by okonech

## Current Behavior

DetailsList allows passing the "getKey" prop along with a "selection" prop. This is confusing to users, since the "getKey" prop function will never be called. the Selection object passed in the "selection" prop either explicitly declares a getKey function, or uses the default getKey implementation (item) => item.key.

## New Behavior

DetailsList has been modified to no longer allow "getKey" and "selection" props to be passed simultaneously. The "getKey" property is never used if a Selection object is passed. Either the "getKey" prop from the Selection object is used, or Selection's default getKey implementation (item) => item.key is used, but never the "getKey" prop passed to DetailsList. Making "getKey" and "selection" mutually exclusive DetailsList properties prevents users from making this mistake.

## Related Issue(s)

(https://github.com/microsoft/fluentui/issues/23614)

Fixes #

2022-07-24 13:45 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/3a4adc9678288e62d86487b84c6e3a4ce55cfae5'>3a4adc9678288e62d86487b84c6e3a4ce55cfae5</a></sub>
<div id="bundleSizeComment9423"/>

2022-07-24 14:02 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/BaseButton-mount_base.html">781</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/BaseButton-mount.html">777</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Breadcrumb-mount_base.html">2372</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Breadcrumb-mount.html">2363</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Checkbox-mount_base.html">2226</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Checkbox-mount.html">2213</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/CheckboxBase-mount_base.html">1940</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/CheckboxBase-mount.html">1936</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/ChoiceGroup-mount_base.html">4070</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/ChoiceGroup-mount.html">4104</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/ComboBox-mount_base.html">844</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/ComboBox-mount.html">840</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/CommandBar-mount_base.html">9059</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/CommandBar-mount.html">9095</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/ContextualMenu-mount_base.html">10230</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/ContextualMenu-mount.html">10076</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DefaultButton-mount_base.html">981</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DefaultButton-mount.html">976</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DetailsRow-mount_base.html">3308</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DetailsRow-mount.html">3294</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DetailsRowFast-mount_base.html">3275</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DetailsRowFast-mount.html">3256</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DetailsRowNoStyles-mount_base.html">3142</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DetailsRowNoStyles-mount.html">3139</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Dialog-mount_base.html">2413</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Dialog-mount.html">2411</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DocumentCardTitle-mount_base.html">159</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/DocumentCardTitle-mount.html">160</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Dropdown-mount_base.html">2860</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Dropdown-mount.html">2863</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/FocusTrapZone-mount_base.html">1612</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/FocusTrapZone-mount.html">1620</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/FocusZone-mount_base.html">1523</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/FocusZone-mount.html">1570</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>IconButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/IconButton-mount_base.html">1498</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/IconButton-mount.html">1524</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Label</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Label-mount_base.html">291</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24048/perf-test/Label-mount.html">303</a></td>
            <td>5000</td>
             [...]

2022-09-14 13:51 UTC, okonech commented
@spmonahan Could you please take a look at this?

2022-09-14 21:02 UTC, spmonahan commented
@okonech Thanks for the PR and sorry it's taken me a bit to look at it.

I agree that the existing behavior is confusing but this PR is a breaking API change so we cannot accept it as-is.

In reviewing your PR I looked into `Selection`'s implementation came across [this comment in Selection.ts](https://github.com/microsoft/fluentui/blob/master/packages/utilities/src/selection/Selection.ts#L11-L12):

```ts
/** Custom logic to generate item keys. Required if `TItem` does not have a `key` property. */
  getKey?: (item: TItem, index?: number) => string | number;
```

Of course this is far from ideal because not only do you have to read the Fluent source code to be aware of it, but it's also counterintuitive that you'd need to provide `getKey()` in two places. At a minimum we can do better by demonstrating the correct usage for Selection and getKey in the docs.

Perhaps there is also an opportunity to change [the way selection is initialized in `DetailsList` instead of changing the API](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/DetailsList/DetailsList.base.tsx#L806-L812)?

What do you think?

cc @behowell

2022-09-14 21:03 UTC, spmonahan requested changes
This change is a breaking API change. Putting a block on merging it while other options are discussed.

2022-09-14 21:19 UTC, okonech commented
This gets a little wonky, but the simplest non-breaking change would be a new method for the Selection object:  setGetKey(getKey: (item: TItem, index?: number) => string | number) : void. Then in the referenced code, we would update the passed selection object with the passed getKey implementation.

It would be cleaner to instead spread the props of the Selection object passed to DetailsList and create a new Selection object (plus the DetailsList's implementation of getKey if a getKey was not provided)

`this._selection =
      props.selection ||
      new Selection({...[spread props.selection values], getKey: props.getKey});`

 but that might break use cases where the users rely on their manually created Selection object's reference being passed in some way. What do you think?

2022-09-27 22:26 UTC, okonech commented
@spmonahan do you have any thoughts?

2022-11-10 18:45 UTC, okonech commented
@spmonahan I've made the change to revert the breaking types change. The PR is now limited to warning users when they use the selection and getKey properties as they are intended to be mutually exclusive. This also fixes the recommended storybook example to follow suit.

2022-11-10 21:09 UTC, spmonahan approved these changes

2022-11-28 01:35 UTC, okonech commented
@ThomasMichon could you please take a look at this?

2023-03-10 19:05 UTC, okonech commented
@ThomasMichon ping :)

2023-03-10 23:03 UTC, fabricteam commented
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

2023-05-15 17:19 UTC, okonech commented
@ThomasMichon could you please review?

2023-05-15 19:37 UTC, fabricteam commented on change/@fluentui-react-519e3c9c-d7fd-40f6-b9f7-6a2d2e1af28f.json
> +{
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=24048&commitId=f4433ae2dc55f2b8fb80420cf282c0bfaa3ee2e6&env=prod)

✅ There was 0 screenshots added, 2 screenshots removed, 1045 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Removed|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Removed|

</details>


<div id="vrtCommentfluentuiv8"/>

2023-05-15 23:02 UTC, ThomasMichon approved these changes

2023-05-16 00:04 UTC, fabricteam commented
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

2023-05-16 17:18 UTC, khmakoto commented
/azp run Fluent UI React - PR and CI

2023-05-16 17:48 UTC, merged