chore: move trigger methods to its own package `react-trigger`
microsoft/fluentui pull request #24923
Opened 2022-09-23 10:29 UTC by bsunderhus

1. Marks all trigger specific methods on `react-utilities` as deprecated
2. Move trigger methods from `@fluentui/react-utilities` to `@fluentui/react-trigger`

2022-09-23 10:40 UTC, fabricteam commented
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContext.fixture.js'>createContext</abbr>                                                                    |          `533 B`<br />`341 B` |
| <samp>global-context</samp> <br /> <abbr title='bundle-size/createContextSelector.fixture.js'>createContextSelector</abbr>                                                    |          `554 B`<br />`348 B` |
| <samp>react-accordion</samp> <br /> <abbr title='bundle-size/Accordion.fixture.js'>Accordion (including children components)</abbr>                                           |   `78.914 kB`<br />`24.06 kB` |
| <samp>react-alert</samp> <br /> <abbr title='bundle-size/Alert.fixture.js'>Alert</abbr>                                                                                       |  `83.511 kB`<br />`20.921 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/Avatar.fixture.js'>Avatar</abbr>                                                                                    |  `48.381 kB`<br />`13.696 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroup.fixture.js'>AvatarGroup</abbr>                                                                          |    `14.95 kB`<br />`5.989 kB` |
| <samp>react-avatar</samp> <br /> <abbr title='bundle-size/AvatarGroupItem.fixture.js'>AvatarGroupItem</abbr>                                                                  |  `68.349 kB`<br />`19.039 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/Badge.fixture.js'>Badge</abbr>                                                                                       |     `22.6 kB`<br />`7.205 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/CounterBadge.fixture.js'>CounterBadge</abbr>                                                                         |   `23.503 kB`<br />`7.497 kB` |
| <samp>react-badge</samp> <br /> <abbr title='bundle-size/PresenseBadge.fixture.js'>PresenceBadge</abbr>                                                                       |    `24.05 kB`<br />`7.067 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/Button.fixture.js'>Button</abbr>                                                                                    |   `36.119 kB`<br />`9.647 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/CompoundButton.fixture.js'>CompoundButton</abbr>                                                                    |   `43.144 kB`<br />`10.86 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/MenuButton.fixture.js'>MenuButton</abbr>                                                                            |  `38.813 kB`<br />`10.551 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/SplitButton.fixture.js'>SplitButton</abbr>                                                                          |  `46.228 kB`<br />`11.933 kB` |
| <samp>react-button</samp> <br /> <abbr title='bundle-size/ToggleButton.fixture.js'>ToggleButton</abbr>                                                                        |  `51.888 kB`<br />`11.127 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.All.fixture.js'>Card - All</abbr>                                                                                |  `67.002 kB`<br />`19.261 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/Card.fixture.js'>Card</abbr>                                                                                          |  `62.684 kB`<br />`18.177 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardFooter.fixture.js'>CardFooter</abbr>                                                                              |    `8.561 kB`<br />`3.601 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardHeader.fixture.js'>CardHeader</abbr>                                                                              |     `9.604 kB`<br />`3.94 kB` |
| <samp>react-card</samp> <br /> <abbr title='bundle-size/CardPreview.fixture.js'>CardPreview</abbr>                                                                            |    `8.662 kB`<br />`3.656 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Combobox.fixture.js'>Combobox (including child components)</abbr>                                                 |  `74.636 kB`<br />`24.186 kB` |
| <samp>react-combobox</samp> <br /> <abbr title='bundle-size/Dropdown.fixture.js'>Dropdown (including child components)</abbr>                                                 |  `74.236 kB`<br />`24.086 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> |  `188.689 kB`<br />`52.37 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `33.394 kB`<br />`11.007 kB` |
| <samp>react-dialog</samp> <br /> <abbr title='bundle-size/Dialog.fixture.js'>Dialog (including children components)</abbr>                                                    |  `82.755 kB`<br />`24.581 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                                                                                 |   `16.459 kB`<br />`5.902 kB` |
| <samp>react-image</samp> <br /> <abbr title='bundle-size/Image.fixture.js'>Image</abbr>                                                                                       |    `10.78 kB`<br />`4.264 kB` |
| <samp>react-input</samp> <br /> <abbr title='bundle-size/Input.fixture.js'>Input</abbr>                                                                                       |   `23.757 kB`<br />`7.704 kB` |
| <samp>react-label</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Label</abbr>                                                                                       |     `9.338 kB`<br />`3.86 kB` |
| <samp>react-link</samp> <br /> <abbr title='bundle-size/Label.fixture.js'>Link</abbr>                                                                                         |   `11.784 kB`<br />`4.867 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          | `116.589 kB`<br />`35.777 kB` |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `119.658 kB`<br />`36.296 kB` |
| <samp>react-overflow</samp> <br /> <abbr title='bundle-size/hooks.fixture.js'>hooks only</abbr>                                                                               |   `10.685 kB`<br />`4.104 kB` |
| <samp>react-popover</samp> <br /> <abbr title='bundle-size/Popover.fixture.js'>Popover</abbr>                                                                                 | `102.963 kB`<br />`31.553 kB` |
| <samp>react-portal</samp> <br /> <abbr title='bundle-size/Portal.fixture.js'>Portal</abbr>                                                                                    |   `10.576 kB`<br />`3.875 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                      [...]

2022-09-23 10:41 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/Avatar-mount_base.html">1263</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/Avatar-mount.html">1272</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/Button-mount_base.html">938</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/Button-mount.html">932</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/FluentProvider-mount_base.html">1536</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/FluentProvider-mount.html">1488</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/FluentProviderWithTheme-mount_base.html">574</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/FluentProviderWithTheme-mount.html">585</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">543</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">544</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">577</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">563</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/MakeStyles-mount_base.html">1947</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/MakeStyles-mount.html">1947</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/SpinButton-mount_base.html">2315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/24923/perf-test-react-components/SpinButton-mount.html">2306</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2022-09-26 13:31 UTC, ling1726 submitted a review, later dismissed

2022-09-26 13:32 UTC, ling1726 commented on packages/react-components/react-dialog/package.json
> +    "@fluentui/react-trigger": "^9.0.0-alpha.0",
this should not be an alpha package, especially since we moved it out of a stable package

2022-09-27 07:23 UTC, ling1726 commented on change/@fluentui-react-trigger-878d2c89-74e6-475d-bd81-c43652fb8f57.json
> +  "type": "prerelease",
```suggestion
  "type": "patch",
```

you should revert the manual bump you did and just change the change type in the change file. Beachball will automatically bump it to the next available non-prerelease version

This is why I'm not a fan of magic tools like beachball :D

2022-09-27 07:23 UTC, ling1726 commented on packages/react-components/react-trigger/package.json
> +  "version": "9.0.0",
```suggestion
  "version": "9.0.0-alpha.0",
```

2022-09-27 07:24 UTC, ling1726 commented on packages/react-components/react-trigger/package.json
> +  "version": "9.0.0",
Please also update `disallowedChangeTypes`

2022-09-27 07:33 UTC, ling1726 approved these changes

2022-09-29 18:02 UTC, behowell reviewed
This change looks good technically. However, the description doesn't say why it's necessary to move this into a separate package. I'm worried about excessive proliferation of packages if we start moving each utility to its own package. Could you update the description with more details about what problem this is solving?

If you'd like, you can set this PR to auto-merge after updating the description, so it will merge once I see the update and approve.

Thanks!

2022-09-30 19:50 UTC, behowell requested changes
So it sounds like this is refactoring; not solving a technical problem, right? Before making a new package for this, it would be good to have a plan for how we decide when a utility should live in react-utilities vs. its own package. That way we can have a consistent and predictable set of packages. 

If the goal is to keep related utilities together, then perhaps they should just be in a sub-folder of react-utilities, instead of their own package.

Or, if the goal is to separate out the fluentui-isms like triggers and slots, out from general-purpose utilities, then perhaps we name this package `react-core` or something, and move the slots and other core functionality into it.

Would it be possible to write a (short?) RFC about how that would work, and discuss it with the team at the next tech sync?

2022-10-03 08:29 UTC, bsunderhus commented
> So it sounds like this is refactoring; not solving a technical problem, right? 

Yes, this is definitely just a refactoring, and a simple one.

> If the goal is to keep related utilities together, then perhaps they should just be in a sub-folder of react-utilities, instead of their own package.

> Or, if the goal is to separate out the fluentui-isms like triggers and slots, out from general-purpose utilities, then perhaps we name this package react-core or something, and move the slots and other core functionality into it.

The problem is not just splitting from general-purpose utilities methods, its more about the priority those domain specific utilities require in our own library.

The way I see utilities provided on the `hooks` are simple generic use case hooks that can be easily documented with comments. On the case of both slots and triggers _utilities_ on the other hand, they have their own domain and its very specific use cases. Demanding proper documentation and examples on our side to ensure proper usage, simply adding comments doesn't get this done.

I believe a `react-core` package would end up being equivalent to our current approach of dropping everything related in the same folder. By splitting those domain specific cases we're giving them the actual relevance they deserve to ensure we'll have them properly documented (which is not necessarily the case at the moment), as an undocumented package is way more critical than an undocumented folder.

2022-10-03 09:49 UTC, bsunderhus commented
After internal discussion, I think it's a majority decision to keep the current folder structure the way it is, on the addendum of a commitment on our side for better documentation on those domain specific folders.

2022-10-03 09:49 UTC, closed without merging