fix: Menu triggers no longer take focus when they are mounted
microsoft/fluentui pull request #25016
Opened 2022-09-29 17:34 UTC by behowell

## Current Behavior

Menu triggers get focus when they're first mounted. This is likely a regression from #24738.

## New Behavior

Restore the `shouldHandleKeyboardRef` check to `useMenu_unstable`.

@bsunderhus I'm not familiar with the reason that it was removed in the first place. If this is not the correct fix, please assign the issue to yourself so you can make the correct fix. Thanks!

## Related Issue(s)

* Fixes #24981

2022-09-29 17:44 UTC, fabricteam commented
## 📊 Bundle size report

| Package & Exports                                                                                                                                                             |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                 Change |
| :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `189.156 kB`<br />`52.385 kB` | `189.209 kB`<br />`52.401 kB` | `53 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /><br />`16 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /> |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.fixture.js'>Menu (including children components)</abbr>                                                          |  `116.718 kB`<br />`35.78 kB` | `116.771 kB`<br />`35.786 kB` |  `53 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /><br />`6 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /> |
| <samp>react-menu</samp> <br /> <abbr title='bundle-size/Menu.Selectable.fixture.js'>Menu (including selectable components)</abbr>                                             | `119.787 kB`<br />`36.289 kB` |  `119.84 kB`<br />`36.296 kB` |  `53 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /><br />`7 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /> |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                  |       Size (minified/GZIP) |
| -------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr> | `33.4 kB`<br />`11.008 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                              | `5.857 kB`<br />`1.978 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0885025f43076ebdf3a395cfb6ae65b3304cc5b2'>0885025f43076ebdf3a395cfb6ae65b3304cc5b2</a></sub>
<div id="bundleSizeComment9423"/>

2022-09-29 17:49 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/Avatar-mount_base.html">1559</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/Avatar-mount.html">1565</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/Button-mount_base.html">1121</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/Button-mount.html">1127</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/FluentProvider-mount_base.html">1883</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/FluentProvider-mount.html">1923</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/FluentProviderWithTheme-mount_base.html">768</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/FluentProviderWithTheme-mount.html">769</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">703</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">694</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">742</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">738</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/MakeStyles-mount_base.html">2314</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/MakeStyles-mount.html">2293</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/SpinButton-mount_base.html">2993</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25016/perf-test-react-components/SpinButton-mount.html">3024</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2022-10-03 17:39 UTC, ling1726 requested changes
The original issue filed by @smhigley was #24680

Let's discuss this first to make sure we know what our focus requirements are for mouse users

2022-10-03 18:00 UTC, ling1726 approved these changes
It seems this bug is more serious than I thought. I think it makes more sense to merge this PR and reopen #24680

2022-10-03 18:35 UTC, merged