ProgressField implementation and stories
microsoft/fluentui pull request #25103
Opened 2022-10-05 22:03 UTC by tomi-msft

This PR is to add `ProgressField` to the `Field` component. `ProgressField` will add a label and description to the `Progress` component, as well as allowing for `success`, `error`, and `warning` states.

2022-10-05 22:14 UTC, fabricteam commented
## 📊 Bundle size report

| Package & Exports                                                                                |   Baseline (minified/GZIP) |                          PR |                                                                                                                                                                                                 Change |
| :----------------------------------------------------------------------------------------------- | -------------------------: | --------------------------: | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-progress</samp> <br /> <abbr title='bundle-size/Progress.fixture.js'>Progress</abbr> | `11.25 kB`<br />`4.514 kB` | `11.302 kB`<br />`4.549 kB` | `52 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /><br />`35 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /> |

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/604033f9ebd55f81635cc479195e36d4030d5c27'>604033f9ebd55f81635cc479195e36d4030d5c27</a></sub>
<div id="bundleSizeComment9423"/>

2022-10-05 22:20 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/Avatar-mount_base.html">1567</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/Avatar-mount.html">1638</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/Button-mount_base.html">1150</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/Button-mount.html">1131</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/FluentProvider-mount_base.html">1908</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/FluentProvider-mount.html">1918</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/FluentProviderWithTheme-mount_base.html">727</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/FluentProviderWithTheme-mount.html">726</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">680</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">648</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">723</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">722</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/MakeStyles-mount_base.html">2222</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/MakeStyles-mount.html">2198</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/SpinButton-mount_base.html">3217</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25103/perf-test-react-components/SpinButton-mount.html">3167</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2022-10-06 17:12 UTC, behowell requested changes
Looks good! Just putting a block on merging until the change file is updated to `prerelease`

2022-10-06 17:12 UTC, behowell commented on change/@fluentui-react-progress-bf837b7d-856a-4256-94fc-ebd888027c86.json
> +  "type": "patch",
This needs to be `prerelease`:
```suggestion
  "type": "prerelease",
```

You'll also need to change the beachball settings in **react-progress/package.json** to:
```
  "beachball": {
    "disallowedChangeTypes": [
      "major",
      "minor",
      "patch"
    ]
  }
```

2022-10-06 17:12 UTC, behowell commented on change/@fluentui-react-progress-bf837b7d-856a-4256-94fc-ebd888027c86.json
> +  "type": "patch",
(This was caused by a bug in the create-package script that I've since fixed in #24763)

2022-10-06 17:12 UTC, behowell commented on apps/vr-tests-react-components/src/stories/Progress.stories.tsx
> +  })
You probably don't need all of these variants for the size tests. They're already covered by the basic test.
```suggestion
  .addStory('Indeterminate with thickness large', () => <Progress className="test-class" thickness="large" />)
```

2022-10-06 17:12 UTC, behowell commented on apps/vr-tests-react-components/src/stories/Progress.stories.tsx
> +  })
thickness medium is the default; you probably don't need this extra test
```suggestion
```

2022-10-06 17:12 UTC, behowell commented on apps/vr-tests-react-components/src/stories/Progress.stories.tsx
> +  )
Ditto: medium is the default
```suggestion
```

2022-10-06 17:12 UTC, behowell commented on apps/vr-tests-react-components/src/stories/Progress.stories.tsx
> +    },
Ditto: these variants should be handled by the Determinate test, and probably aren't needed for this thickness test
```suggestion
```

2022-10-06 17:12 UTC, behowell commented on apps/vr-tests-react-components/src/stories/Progress.stories.tsx
> +storiesOf('Progress converged', module)
Is this file meant for a different PR?

2022-10-06 18:41 UTC, behowell approved these changes

2022-10-06 20:18 UTC, merged