Provide overridable package for Fluent CDN resources
microsoft/fluentui pull request #25396
Opened 2022-10-26 23:59 UTC by ThomasMichon

## Current Behavior

Several subsystems of Fluent make reference to resources on the Fabric CDN. Since many Microsoft and partner apps may need to override these, there are several scattered `initialize___()` functions throughout the Fluent package suite, which take overrides for a `baseUrl` used for a subset of resources from the same CDN.
One challenge this poses is that the more of these initialize flows there are, the more likely it is for a host app to miss calling one, or to just wind up calling it without an override `baseUrl`, causing the default one to be used.
Because only the host should call the callback, it also makes it annoying for library components to depend on their `initialize___()` dependency being called.

## New Behavior

In this PR, a new `@fluentui/cdn` package is introduced, with a single export for `FLUENT_CDN_BASE_URL`. The expectation is that a host app can override this export at *bundle time*, providing code which might emit a different value. Then, all importers in Fluent packages and other code will just wind up with the right value. This will allow Fluent code in the future to 'auto-initialize' their needed icons, since the correct value will be provided dynamically via bundling and not require hard-coding.

2022-10-27 00:03 UTC, ThomasMichon commented on workspace.json
> +    "@fluentui/cdn": {
Is this all I need to do to add a new project? When I run `yarn build` after adding this I'm getting bizarre errors from other unrelated packages.

2022-10-27 00:13 UTC, fabricteam commented
## 📊 Bundle size report

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                        |        Size (minified/GZIP) |
| ------------------------------------------------------------------------------------------------------------------------ | --------------------------: |
| <samp>priority-overflow</samp> <br /> <abbr title='bundle-size/overflow-manager.fixture.js'>createOverflowManager</abbr> |  `3.153 kB`<br />`1.299 kB` |
| <samp>react-divider</samp> <br /> <abbr title='bundle-size/Divider.fixture.js'>Divider</abbr>                            | `16.505 kB`<br />`5.925 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/SingleThemeToken.fixture.js'>Single theme token import</abbr>   |          `69 B`<br />`89 B` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsAllThemes.fixture.js'>Teams: all themes</abbr>             |  `29.65 kB`<br />`6.444 kB` |
| <samp>react-theme</samp> <br /> <abbr title='bundle-size/TeamsLightTheme.fixture.js'>Teams: Light theme</abbr>           | `17.486 kB`<br />`5.057 kB` |
| <samp>react-utilities</samp> <br /> <abbr title='bundle-size/SSRProvider.fixture.js'>SSRProvider</abbr>                  |        `180 B`<br />`159 B` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/9cbf82e22c21e744601adcd6a3d064e406d015d8'>9cbf82e22c21e744601adcd6a3d064e406d015d8</a></sub>
<div id="bundleSizeComment9423"/>

2022-10-27 00:21 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/Avatar-mount_base.html">1617</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/Avatar-mount.html">1644</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/Button-mount_base.html">1157</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/Button-mount.html">1154</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/FluentProvider-mount_base.html">1930</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/FluentProvider-mount.html">1919</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/FluentProviderWithTheme-mount_base.html">701</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/FluentProviderWithTheme-mount.html">716</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">655</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">667</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">708</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">703</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/MakeStyles-mount_base.html">2229</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/MakeStyles-mount.html">2208</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/SpinButton-mount_base.html">3166</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-react-components/SpinButton-mount.html">3215</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2022-10-27 00:26 UTC, fabricteam commented
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
CarouselMinimalPerf.default | [479](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/CarouselMinimalPerf.default.html) | [433](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.11:1
AlertMinimalPerf.default | [265](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/AlertMinimalPerf.default.html) | [240](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.1:1
TreeWith60ListItems.default | [163](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/TreeWith60ListItems.default.html) | [149](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.09:1
ChatDuplicateMessagesPerf.default | [269](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [252](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.07:1
GridMinimalPerf.default | [344](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/GridMinimalPerf.default.html) | [322](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.07:1
FormMinimalPerf.default | [382](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/FormMinimalPerf.default.html) | [359](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.06:1
SkeletonMinimalPerf.default | [350](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/SkeletonMinimalPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/SkeletonMinimalPerf.default_base.html) | 1.06:1
BoxMinimalPerf.default | [341](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/BoxMinimalPerf.default.html) | [325](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.05:1
ItemLayoutMinimalPerf.default | [1165](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ItemLayoutMinimalPerf.default.html) | [1109](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ItemLayoutMinimalPerf.default_base.html) | 1.05:1
ListNestedPerf.default | [568](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ListNestedPerf.default.html) | [540](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ListNestedPerf.default_base.html) | 1.05:1
ListWith60ListItems.default | [621](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ListWith60ListItems.default.html) | [593](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ListWith60ListItems.default_base.html) | 1.05:1
RadioGroupMinimalPerf.default | [444](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [423](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.05:1
SegmentMinimalPerf.default | [335](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/SegmentMinimalPerf.default.html) | [319](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/SegmentMinimalPerf.default_base.html) | 1.05:1
AttachmentSlotsPerf.default | [1124](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/AttachmentSlotsPerf.default.html) | [1076](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/AttachmentSlotsPerf.default_base.html) | 1.04:1
DividerMinimalPerf.default | [343](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/DividerMinimalPerf.default.html) | [331](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.04:1
TableManyItemsPerf.default | [1872](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/TableManyItemsPerf.default.html) | [1797](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.04:1
TreeMinimalPerf.default | [797](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/TreeMinimalPerf.default.html) | [767](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/TreeMinimalPerf.default_base.html) | 1.04:1
ImageMinimalPerf.default | [379](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ImageMinimalPerf.default.html) | [369](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.03:1
InputMinimalPerf.default | [1164](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/InputMinimalPerf.default.html) | [1128](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.03:1
MenuMinimalPerf.default | [831](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/MenuMinimalPerf.default.html) | [804](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/MenuMinimalPerf.default_base.html) | 1.03:1
ProviderMinimalPerf.default | [405](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ProviderMinimalPerf.default.html) | [395](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.03:1
TextAreaMinimalPerf.default | [460](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/TextAreaMinimalPerf.default.html) | [445](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.03:1
CheckboxMinimalPerf.default | [2083](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/CheckboxMinimalPerf.default.html) | [2037](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/CheckboxMinimalPerf.default_base.html) | 1.02:1
DialogMinimalPerf.default | [763](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/DialogMinimalPerf.default.html) | [750](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/DialogMinimalPerf.default_base.html) | 1.02:1
HeaderSlotsPerf.default | [745](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/HeaderSlotsPerf.default.html) | [728](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.02:1
ListMinimalPerf.default | [510](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ListMinimalPerf.default.html) | [499](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.02:1
SliderMinimalPerf.default | [1606](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/SliderMinimalPerf.default.html) | [1577](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1341](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1333](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.01:1
ButtonSlotsPerf.default | [557](https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test-northstar/ButtonSlotsPerf.default.html) | [550](https://fluentuipr.z22.web.core.window [...]

2022-11-02 12:34 UTC, Hotell requested changes
I don't have all context regarding those static assets and it would be great if you could provide more information regarding 
> The expectation is that a host app can override this export at bundle time, providing code which might emit a different value.

How would that override look like ?

If there is a real production need to be able to configure some internals in our packages it should be done on environment level in user land. Thus setting demanded env vars when packaging apps etc.

2022-11-07 21:02 UTC, ThomasMichon commented
@Hotell The idea here is that an app's final Webpack config could use `NormalModuleReplacementPlugin` or similar to replace the `@fluentui/cdn` module with a different implementation that has the same exports, but these value can now be computed on-demand based on that app's current configuration, perhaps by reading an app-specific window global, likely burned into the page by the server logic and not set in client code.

The reason not to use a pre-set 'environment value' is one of timing: it's actually quite difficult to ensure that the globals are set *before* the Fluent modules start loading and initializing, leading to app code containing a lot of 'defensive' calls to write the Fluent globals over and over. Our codebase has a lot of random calls to `initializeIcons(baseUrl)` just because we can't be sure whether we're the first code to run before loading Fluent.

Allowing the override at bundle-time permanently fixes the sequencing issue: the module can be replaced such that the final `export` is produced by invoking some logic, and that `export` doesn't get invoked until it is first read by Fluent code.

2022-11-07 21:31 UTC, bigbadcapers commented
Hey Thomas, lmk if you need a review from me in terms of UX or impact to the filetype system. I think what you're doing here is more about centralizing the CDN URL version which i am all in favor of!  Also, a few months back, someone opened this ask, probably related, to try making the filetype icons module easier to leverage separately. Not sure if there's anything that can be improved there since you're making broad changes:

https://github.com/microsoft/fluentui/pull/24402

2022-11-08 00:30 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/BaseButton-mount_base.html">1429</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/BaseButton-mount.html">1441</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/Breadcrumb-mount_base.html">3475</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/Breadcrumb-mount.html">3493</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/Checkbox-mount_base.html">3254</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/Checkbox-mount.html">3164</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/CheckboxBase-mount_base.html">2894</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/CheckboxBase-mount.html">2802</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/ChoiceGroup-mount_base.html">5364</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/ChoiceGroup-mount.html">5401</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/ComboBox-mount_base.html">1533</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/ComboBox-mount.html">1480</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/CommandBar-mount_base.html">11448</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/CommandBar-mount.html">11553</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/ContextualMenu-mount_base.html">13057</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/ContextualMenu-mount.html">12963</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DefaultButton-mount_base.html">1660</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DefaultButton-mount.html">1706</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DetailsRow-mount_base.html">4381</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DetailsRow-mount.html">4419</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DetailsRowFast-mount_base.html">4498</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DetailsRowFast-mount.html">4384</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DetailsRowNoStyles-mount_base.html">4244</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DetailsRowNoStyles-mount.html">4173</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/Dialog-mount_base.html">3724</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/Dialog-mount.html">3688</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DocumentCardTitle-mount_base.html">691</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/DocumentCardTitle-mount.html">703</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/Dropdown-mount_base.html">3953</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/Dropdown-mount.html">3915</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/FocusTrapZone-mount_base.html">2426</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/FocusTrapZone-mount.html">2456</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/FocusZone-mount_base.html">2356</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/FocusZone-mount.html">2329</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/GroupedList-mount_base.html">2310</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/GroupedList-mount.html">2649</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/GroupedList-virtual-rerender_base.html">1327</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25396/perf-test/GroupedList-virtual-rerend [...]

2022-11-08 16:56 UTC, bigbadcapers approved these changes
From a ease-of-package-adoption standpoint, it makes it better to adopt, while not changing any of the UX impact of the affected packages. Pls note I did not review for code hygiene, will defer to experts there.

2022-11-09 10:43 UTC, Hotell commented
@ThomasMichon 

thanks for additional context.

Based on what you're saying I see no difference with approach I proposed with no additional churn/magic needed.  The approach with env variables set during bundling time for various environments additionally supported by global overrides (window by server) should be all that's needed.

Also note that tight coupling to particular bundling solution (webpack) is something we wanna avoid in general as we support any JS ecosystem.

2022-11-11 19:13 UTC, ThomasMichon commented
Replacing a whole imported module is something most bundlers can do quite easily. You can do it in RequireJS or even direct `type="module"` script tags or the new Web Bundles spec.

The goal would be to replace the code like this:
```ts
export const FLUENT_CDN_BASE_URL = '----';
```
with code like this:
```ts
import getFluentCdnUrl from 'our/app';

const fluentCdnBaseUrl = getFluentCdnUrl();

export const FLUENT_CDN_BASE_URL = fluentCdnBaseUrl;
```
In this version, the value of `FLUENT_CDN_BASE_URL` is not actually a constant bundled into the code, it's instead a value computed at runtime during initialization of the modules.

2022-11-16 12:01 UTC, Hotell commented
**Update/:**

> We had offline convo with @ThomasMichon

Ideal scenario would be to have this since day 1 as env variable defined in user land during builds instead of hard coded URL in design system code-base based. Unfortunately doing that would be a breaking change thus we agreed on following approach:


 - extracting the CDN base to existing package that matches most the domain boundary for this use case.

2022-11-16 12:03 UTC, Hotell approved these changes

2022-11-16 17:22 UTC, GeoffCoxMSFT approved these changes

2023-02-02 19:17 UTC, fabricteam commented on change/@fluentui-font-icons-mdl2-9d4619ab-bbec-48fc-ba00-2d2d4717d321.json
> +{
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 4 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25396&commitId=98b9409aa77a5d88b4c6402a7ec9e93cd55d0294&env=prod)

✅ There was 4 screenshots added, 0 screenshots removed, 1041 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 4 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Root.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Root.Narrow - Overflow menu.chromium.png|0| Added|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Added|

</details>


<div id="vrtCommentfluentuiv8"/>

2023-02-08 23:48 UTC, fabricteam commented
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluentuiv8"/>

2023-02-16 21:32 UTC, micahgodbolt commented
Note that this CDN in question is predominantly used in v8 (and hosts old Core, JS and other deprecated libraries). So including it in style-utilities certainly makes sense seeing that the readme there says

> This gives you access to styling-related constants, utilities, and Fabric Core style classes through JavaScript.

In the future, if we want to use these CDN files in v9, we need to find a way to do so where v9 does not depend on style-utilities, as it would introduce unwanted dependencies on merge-styles and other packages.

2023-02-16 21:33 UTC, micahgodbolt approved these changes

2023-02-16 21:37 UTC, sopranopillow approved these changes

2023-02-16 23:15 UTC, khmakoto approved these changes

2023-03-01 00:31 UTC, fabricteam commented on change/@fluentui-font-icons-mdl2-9d4619ab-bbec-48fc-ba00-2d2d4717d321.json
> +{
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the 2 screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=25396&commitId=b2575c816da91c66fc06b85dc881ad2829876438&env=prod)

✅ There was 2 screenshots added, 0 screenshots removed, 1043 screenshots unchanged, 0 screenshots with different dimensions and 0 screenshots with visible difference.


  <details><summary><b>unknown</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Pivot - Overflow.Tabs - RTL.Narrow - Last tab selected.chromium.png|0| Added|
|Pivot - Overflow.Tabs - RTL.Narrow - Overflow menu.chromium.png|0| Added|

</details>


<div id="vrtCommentfluentuiv8"/>

2023-03-03 23:56 UTC, merged