chore(react-recipes): `@fluentui/react-recipes` scaffold
microsoft/fluentui pull request #25578
Opened 2022-11-08 20:00 UTC by sopranopillow

This PR adds the `react-recipes` package to `react-components`. This package will host the recipes that will be created in the future, this package must never be released. It was added as a package and not a folder/app for ease of use with v9's docsite and v9's storybook.

## Related Issue(s)

Related #25512

2022-11-08 20:06 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/6ab9ad73f61226c779bd6bc297daa12b11791551'>6ab9ad73f61226c779bd6bc297daa12b11791551</a></sub>
<div id="bundleSizeComment9423"/>

2022-11-08 20:12 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/Avatar-mount_base.html">1295</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/Avatar-mount.html">1286</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/Button-mount_base.html">913</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/Button-mount.html">906</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/FluentProvider-mount_base.html">1476</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/FluentProvider-mount.html">1485</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/FluentProviderWithTheme-mount_base.html">580</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/FluentProviderWithTheme-mount.html">567</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">542</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">540</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">578</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">586</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/MakeStyles-mount_base.html">1967</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/MakeStyles-mount.html">1958</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/SpinButton-mount_base.html">2315</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-react-components/SpinButton-mount.html">2338</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2022-11-08 20:24 UTC, fabricteam commented
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
PortalMinimalPerf.default | [149](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/PortalMinimalPerf.default.html) | [136](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/PortalMinimalPerf.default_base.html) | 1.1:1
BoxMinimalPerf.default | [306](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/BoxMinimalPerf.default.html) | [296](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.03:1
GridMinimalPerf.default | [303](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/GridMinimalPerf.default.html) | [294](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.03:1
VideoMinimalPerf.default | [620](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/VideoMinimalPerf.default.html) | [604](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/VideoMinimalPerf.default_base.html) | 1.03:1
AccordionMinimalPerf.default | [121](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/AccordionMinimalPerf.default.html) | [119](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.02:1
ButtonMinimalPerf.default | [139](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ButtonMinimalPerf.default.html) | [136](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ButtonMinimalPerf.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [1024](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [1000](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ButtonOverridesMissPerf.default_base.html) | 1.02:1
DropdownMinimalPerf.default | [2190](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/DropdownMinimalPerf.default.html) | [2156](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/DropdownMinimalPerf.default_base.html) | 1.02:1
ListNestedPerf.default | [468](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ListNestedPerf.default.html) | [459](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ListNestedPerf.default_base.html) | 1.02:1
LoaderMinimalPerf.default | [270](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/LoaderMinimalPerf.default.html) | [266](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.02:1
RosterPerf.default | [1698](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/RosterPerf.default.html) | [1672](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/RosterPerf.default_base.html) | 1.02:1
RadioGroupMinimalPerf.default | [392](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/RadioGroupMinimalPerf.default.html) | [385](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/RadioGroupMinimalPerf.default_base.html) | 1.02:1
ReactionMinimalPerf.default | [334](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ReactionMinimalPerf.default.html) | [329](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ReactionMinimalPerf.default_base.html) | 1.02:1
AvatarMinimalPerf.default | [162](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/AvatarMinimalPerf.default.html) | [160](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.01:1
ButtonSlotsPerf.default | [420](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ButtonSlotsPerf.default.html) | [417](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.01:1
CarouselMinimalPerf.default | [354](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/CarouselMinimalPerf.default.html) | [351](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/CarouselMinimalPerf.default_base.html) | 1.01:1
DividerMinimalPerf.default | [317](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/DividerMinimalPerf.default.html) | [313](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.01:1
DropdownManyItemsPerf.default | [542](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/DropdownManyItemsPerf.default.html) | [534](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.01:1
ImageMinimalPerf.default | [337](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ImageMinimalPerf.default.html) | [333](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ImageMinimalPerf.default_base.html) | 1.01:1
InputMinimalPerf.default | [862](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/InputMinimalPerf.default.html) | [855](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/InputMinimalPerf.default_base.html) | 1.01:1
LayoutMinimalPerf.default | [312](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/LayoutMinimalPerf.default.html) | [308](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.01:1
ListCommonPerf.default | [522](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ListCommonPerf.default.html) | [518](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ListCommonPerf.default_base.html) | 1.01:1
MenuButtonMinimalPerf.default | [1351](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [1335](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.01:1
PopupMinimalPerf.default | [557](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/PopupMinimalPerf.default.html) | [553](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/PopupMinimalPerf.default_base.html) | 1.01:1
ProviderMergeThemesPerf.default | [986](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ProviderMergeThemesPerf.default.html) | [975](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/ProviderMergeThemesPerf.default_base.html) | 1.01:1
SplitButtonMinimalPerf.default | [3290](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/SplitButtonMinimalPerf.default.html) | [3268](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/SplitButtonMinimalPerf.default_base.html) | 1.01:1
TableManyItemsPerf.default | [1572](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/TableManyItemsPerf.default.html) | [1554](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/TableManyItemsPerf.default_base.html) | 1.01:1
TableMinimalPerf.default | [358](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/TableMinimalPerf.default.html) | [353](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/TableMinimalPerf.default_base.html) | 1.01:1
TextAreaMinimalPerf.default | [410](https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test-northstar/TextAreaMinimalPerf.default.html) | [404](https://fluentuipr.z22.web.core.windows.net/pul [...]

2022-11-08 20:27 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/BaseButton-mount_base.html">1188</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/BaseButton-mount.html">1198</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/Breadcrumb-mount_base.html">2942</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/Breadcrumb-mount.html">2909</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/Checkbox-mount_base.html">2680</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/Checkbox-mount.html">2643</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/CheckboxBase-mount_base.html">2384</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/CheckboxBase-mount.html">2383</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/ChoiceGroup-mount_base.html">4246</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/ChoiceGroup-mount.html">4239</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/ComboBox-mount_base.html">1250</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/ComboBox-mount.html">1191</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/CommandBar-mount_base.html">9564</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/CommandBar-mount.html">9575</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/ContextualMenu-mount_base.html">11646</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/ContextualMenu-mount.html">11464</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DefaultButton-mount_base.html">1363</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DefaultButton-mount.html">1369</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DetailsRow-mount_base.html">3382</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DetailsRow-mount.html">3420</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DetailsRowFast-mount_base.html">3370</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DetailsRowFast-mount.html">3394</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DetailsRowNoStyles-mount_base.html">3240</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DetailsRowNoStyles-mount.html">3208</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/Dialog-mount_base.html">2981</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/Dialog-mount.html">2970</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DocumentCardTitle-mount_base.html">584</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/DocumentCardTitle-mount.html">599</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/Dropdown-mount_base.html">3193</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/Dropdown-mount.html">3185</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/FocusTrapZone-mount_base.html">1998</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/FocusTrapZone-mount.html">1948</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/FocusZone-mount_base.html">1983</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/FocusZone-mount.html">1959</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/GroupedList-mount_base.html">1867</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/GroupedList-mount.html">2072</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/GroupedList-virtual-rerender_base.html">1135</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/25578/perf-test/GroupedList-virtual-rerender [...]

2022-11-09 15:12 UTC, TristanWatanabe approved these changes

2022-11-10 12:28 UTC, Hotell commented
Based on this issue https://github.com/microsoft/fluentui/issues/25512 , the intent is not very clear to me. Could you provide more detailed explanation how is this gonna be used etc ? I don't see reason having this as separate internal package

2022-11-10 12:32 UTC, Hotell requested changes
more context needed  - pls see my comment

2022-11-10 17:02 UTC, closed without merging