Added BreadcrumbItem and BreadcrumbDivider components
microsoft/fluentui pull request #26693
Opened 2023-02-06 18:41 UTC by ValentinaKozlova

This PR is for Breadcrumb structure changes.
Here's the Research task: #26481
The proposed structure is:
Breadcrumb component contains:
- BreadcrumbItem
- BreadcrumbDivider
- OverflowButton

1st commit is generated components.
2nd one contains basic structural changes

2023-02-06 18:53 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/0cbf85cf12a08ff04ac1807a49ca469f92330211'>0cbf85cf12a08ff04ac1807a49ca469f92330211</a></sub>
<div id="bundleSizeComment9423"/>

2023-03-09 14:13 UTC, marcosmoura requested changes

2023-03-09 14:13 UTC, marcosmoura commented on packages/react-components/react-breadcrumb/src/components/Breadcrumb/Breadcrumb.types.ts
> +export type BreadcrumbProps = ComponentProps<Omit<BreadcrumbSlots, 'list'>> & {};
Was there a reason to omit this prop?

2023-03-09 14:13 UTC, marcosmoura commented on packages/react-components/react-breadcrumb/src/components/BreadcrumbDivider/BreadcrumbDivider.test.tsx
> +    expect(result.container).toMatchSnapshot();
Could we use `toMatchInlineSnapshot` instead? In this case, it won't generate a .snap file.

2023-03-09 14:13 UTC, marcosmoura commented on packages/react-components/react-breadcrumb/src/components/BreadcrumbDivider/BreadcrumbDivider.tsx
> +  useBreadcrumbDividerStyles_unstable(state);
It would be a good idea to already include the custom styles hook, like in this PR:
https://github.com/microsoft/fluentui/pull/27078

2023-03-09 14:13 UTC, marcosmoura commented on packages/react-components/react-breadcrumb/src/components/BreadcrumbItem/BreadcrumbItem.test.tsx
> +    expect(result.container).toMatchSnapshot();
Same here

2023-03-09 14:13 UTC, marcosmoura commented on packages/react-components/react-breadcrumb/src/components/BreadcrumbItem/BreadcrumbItem.tsx
> +  useBreadcrumbItemStyles_unstable(state);
Same here.

2023-03-10 13:57 UTC, marcosmoura approved these changes

2023-03-10 14:11 UTC, merged