accordion and accordion item unit tests
microsoft/fluentui pull request #28801
Opened 2023-08-09 22:57 UTC by brianchristopherbrady

Adds `accordion` and `accordion` item unit tests

2023-08-09 23:04 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/c83bfec16fd0d93b1305e5f5aec5d8a62c8f7cb7'>c83bfec16fd0d93b1305e5f5aec5d8a62c8f7cb7</a></sub>
<div id="bundleSizeComment9423"/>

2023-08-09 23:04 UTC, fabricteam commented
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2023-08-15 17:07 UTC, procload requested changes
Looking good! There are a few tests we might want to add, however:
* Do we want to test keyboard navigation? Specifically moving between the elements and expanding/collapsing with the Enter key?
* How can we test whether or not the items are expandable (or not) when disabled? [Check out what I'm doing for the radio group here](https://github.com/microsoft/fluentui/pull/28826/files#diff-284c1170817764783c78596674612e5b50dae8dbd894259d9dcc219f13c929d5R293-R342).
* We should test for the ability to add custom icons and presentation icons. I did something [similar on the CounterBadge component here](https://github.com/microsoft/fluentui/pull/28867/files#diff-1ce40f3696e610e18f1d8ec650c19eac6d36fda965af36496404995d963c428aR24-R81).

2023-08-15 17:08 UTC, procload requested changes
Looking good! There are a few tests we might want to add, however:
* Do we want to test keyboard navigation? Specifically moving between the elements and expanding/collapsing with the Enter key?
* How can we test whether or not the items are expandable (or not) when disabled? [Check out what I'm doing for the radio group here](https://github.com/microsoft/fluentui/pull/28826/files#diff-284c1170817764783c78596674612e5b50dae8dbd894259d9dcc219f13c929d5R293-R342).
* We should test for the ability to add custom icons and presentation icons. I did something [similar on the CounterBadge component here](https://github.com/microsoft/fluentui/pull/28867/files#diff-1ce40f3696e610e18f1d8ec650c19eac6d36fda965af36496404995d963c428aR24-R81).

2023-08-15 21:07 UTC, halerankin commented on packages/web-components/src/accordion/accordion.spec.ts
> +    test.slow();
Two items expanded while in single expand-mode? Is there a use case for this in the Figma?

2023-08-15 21:09 UTC, halerankin approved these changes
w/ comment

2023-08-17 16:33 UTC, procload approved these changes

2023-08-21 03:54 UTC, miroslavstastny approved these changes

2023-08-21 04:01 UTC, merged