bugfix(react-table): add system colors on hover
microsoft/fluentui pull request #30073
Opened 2023-12-14 13:26 UTC by bsunderhus

## New Behavior

1. adds proper [system colors](https://drafts.csswg.org/css-color-4/#css-system-colors) on hover if [forced colors](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) is active

## Related Issue(s)

- Fixes https://github.com/microsoft/fluentui/issues/30070

2023-12-14 13:38 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/Avatar-mount_base.html">582</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/Avatar-mount.html">602</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/Button-mount_base.html">324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/Button-mount.html">306</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/Field-mount_base.html">1087</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/Field-mount.html">1128</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/FluentProvider-mount_base.html">696</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/FluentProvider-mount.html">684</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/FluentProviderWithTheme-mount_base.html">72</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/FluentProviderWithTheme-mount.html">79</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">66</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">67</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">70</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">74</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/MakeStyles-mount_base.html">842</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/MakeStyles-mount.html">854</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/Persona-mount_base.html">1720</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/Persona-mount.html">1624</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/SpinButton-mount_base.html">1331</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30073/perf-test-react-components/SpinButton-mount.html">1366</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2023-12-14 13:40 UTC, fabricteam commented
## 📊 Bundle size report

| Package & Exports                                                                                                     |      Baseline (minified/GZIP) |                            PR |                                                                                                                                                                                                  Change |
| :-------------------------------------------------------------------------------------------------------------------- | ----------------------------: | ----------------------------: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/DataGrid.fixture.js'>DataGrid</abbr>                         | `153.989 kB`<br />`43.372 kB` | `154.364 kB`<br />`43.453 kB` | `375 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /><br />`81 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /> |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/PrimitivesOnly.fixture.js'>Table (Primitives only)</abbr>    |  `43.805 kB`<br />`13.751 kB` |   `44.18 kB`<br />`13.832 kB` | `375 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /><br />`81 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /> |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableAsDataGrid.fixture.js'>Table as DataGrid</abbr>         |  `127.211 kB`<br />`34.66 kB` | `127.586 kB`<br />`34.739 kB` | `375 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /><br />`79 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /> |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSelectionOnly.fixture.js'>Table (Selection only)</abbr> |  `72.389 kB`<br />`19.905 kB` |  `72.764 kB`<br />`20.003 kB` | `375 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /><br />`98 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /> |
| <samp>react-table</samp> <br /> <abbr title='bundle-size/TableSortOnly.fixture.js'>Table (Sort only)</abbr>           |  `70.996 kB`<br />`19.506 kB` |  `71.371 kB`<br />`19.604 kB` | `375 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /><br />`98 B` <img aria-hidden="true" src="https://microsoft.github.io/monosize/images/increase.png" /> |

<details>
<summary>Unchanged fixtures</summary>

| Package & Exports                                                                                                                                                             |          Size (minified/GZIP) |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------: |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ButtonProviderAndTheme.fixture.js'>react-components: Button, FluentProvider & webLightTheme</abbr>              |  `69.816 kB`<br />`20.222 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/MultipleComponents.fixture.js'>react-components: Accordion, Button, FluentProvider, Image, Menu, Popover</abbr> | `208.325 kB`<br />`59.656 kB` |
| <samp>react-components</samp> <br /> <abbr title='bundle-size/ProviderAndTheme.fixture.js'>react-components: FluentProvider & webLightTheme</abbr>                            |  `42.101 kB`<br />`14.024 kB` |
| <samp>react-portal-compat</samp> <br /> <abbr title='bundle-size/PortalCompat.fixture.js'>PortalCompatProvider</abbr>                                                         |    `6.822 kB`<br />`2.299 kB` |

</details>
<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/8012cdf639e843847ee633040994c2d4e135185b'>8012cdf639e843847ee633040994c2d4e135185b</a></sub>
<div id="bundleSizeComment9423"/>

2023-12-14 13:50 UTC, fabricteam commented
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

2023-12-15 07:41 UTC, ling1726 requested changes
Let's discuss the consequences of `forced-color-adjust:none`

2024-01-11 17:05 UTC, ling1726 commented on packages/react-components/react-table/src/components/TableRow/useTableRowStyles.styles.ts
> +        backgroundColor: 'Canvas',
```suggestion
```

you shouldn't need this - that's just the default background I believe

2024-01-11 17:05 UTC, ling1726 approved these changes

2024-01-12 06:30 UTC, merged