Adding azure-theme to v9
microsoft/fluentui pull request #30365
Opened 2024-01-22 23:27 UTC by adr1-jpg

## Previous Behavior

The current themes available for fluent v9 components are: Web Light, Web Dark, Teams Light, Teams Dark, and Teams High Contrast.
<img width="220"  alt="Screenshot of dropdown menu labeled theme, drop down options read: Web Light, Web Dark, Teams Light, Teams Dark, Teams High Contrast." src="https://github.com/adr1-jpg/fluentui/assets/123518484/47bafed4-fb80-4057-b088-9dc542e36500">

Teams Light Theme Applied:
<img width="626" alt="Screenshot of Fluent v9 buttons with appearances from left to right: default, primary, outline, subtle, transparent. Primary color is purple. Background is light gray" src="https://github.com/adr1-jpg/fluentui/assets/123518484/7b415134-dfdb-4919-b6f7-6b7bb4ac9975">
Teams Dark Theme Applied:
<img width="626" alt="Screenshot of Fluent v9 buttons with appearances from left to right: default, primary, outline, subtle, transparent. Primary color is purple. Background is dark gray." src="https://github.com/adr1-jpg/fluentui/assets/123518484/2485a802-da54-4b88-a120-2c5e8805b30b">

## New Behavior

This update will add azure-themes to fluent v9. It adds Azure Light and Azure Dark to the available themes.

Azure Light Theme Applied:
<img width="626" alt="Screenshot of Fluent v9 buttons with appearances from left to right: default, primary, outline, subtle, transparent. Primary color is Azure blue. Background is light gray." src="https://github.com/adr1-jpg/fluentui/assets/123518484/ab2cac4d-0898-472c-aebe-77831f1fa602">
Azure Dark Theme Applied:
<img width="626" alt="Screenshot of Fluent v9 buttons with appearances from left to right: default, primary, outline, subtle, transparent. Primary color is Azure blue. Background is dark gray." src="https://github.com/adr1-jpg/fluentui/assets/123518484/da7267a9-1fd7-4e37-9d2e-e8d0666e98b3">

## Related Issue(s)

- Fixes #

2024-01-22 23:33 UTC, fabricteam commented
## 📊 Bundle size report

<sub>🤖 This report was generated against <a href='https://github.com/microsoft/fluentui/commit/2314a84349b2e58b54ebe70d4408ef5fc060f43f'>2314a84349b2e58b54ebe70d4408ef5fc060f43f</a></sub>
<div id="bundleSizeComment9423"/>

2024-01-22 23:37 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/Avatar-mount_base.html">666</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/Avatar-mount.html">629</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/Button-mount_base.html">300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/Button-mount.html">299</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/Field-mount_base.html">1115</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/Field-mount.html">1118</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/FluentProvider-mount_base.html">685</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/FluentProvider-mount.html">713</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/FluentProviderWithTheme-mount_base.html">79</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/FluentProviderWithTheme-mount.html">88</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">60</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">66</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">71</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">78</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/MakeStyles-mount_base.html">855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/MakeStyles-mount.html">864</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/Persona-mount_base.html">1818</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/Persona-mount.html">1743</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/SpinButton-mount_base.html">1383</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-react-components/SpinButton-mount.html">1359</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2024-01-22 23:51 UTC, fabricteam commented
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

2024-01-25 00:49 UTC, Jacqueline-ms commented
Thank you for this, Adriana. Looking over the preview URL at this time.

2024-01-26 12:07 UTC, Hotell commented
Im wondering how this aligns with core fluent. are we gonna ship with core theme for every product ? 

maybe we should consider having these themes as separate packages for better domain boundaries and not impacting users with additional javascript.

we should discuss this on tech sync

2024-01-26 17:38 UTC, Jacqueline-ms commented
> Im wondering how this aligns with core fluent. are we gonna ship with core theme for every product ?
> 
> maybe we should consider having these themes as separate packages for better domain boundaries and not impacting users with additional javascript.
> 
> we should discuss this on tech sync

In V7/V8, Azure Theme is its own package. We are open to feedback on how to implement, so the Azure portal can implement when they move to V9.

2024-02-08 14:26 UTC, miroslavstastny commented on packages/tokens/src/utils/createAzureDarkTheme.ts
This file as well as `packages/tokens/src/utils/createAzureLightTheme.ts` should be removed as these are just copies of `createLightTheme()` and `createDarkTheme()` functions.

Azure theme should be created by calling `createLightTheme(azureBrandRamp)`.

2024-02-08 23:27 UTC, miroslavstastny requested changes
For a short term, please implement the azure theme on the application side.
The following code should be sufficient:
```js
import {
  createLightTheme,
  createDarkTheme,
  type BrandVariants
} from '@fluentui/react-components';

const brandAzure: BrandVariants = {
  10: `#092c47`,
  20: `#004578`,
  30: `#043862`,
  40: `#005a9e`,
  50: `#004c87`,
  60: `#106ebe`,
  70: `#0078d4`,
  80: `#0078d4`,
  90: `#0086f0`,
  100: `#69afe5`,
  110: `#1890f1`,
  120: `#c7e0f4`,
  130: `#3aa0f3`,
  140: `#deecf9`,
  150: `#6cb8f6`,
  160: `#eff6fc`,
};

const azureLightTheme = createLightTheme(brandAzure);
const azureDarkTheme = createDarkTheme(brandAzure);
```

(Note: for some reason brand.70 and brand.80 use the same hex values, that should be fixed).

Fluent team will find a solution for hosting the non-core teams and get back to you.

2024-02-09 01:17 UTC, mltejera commented
I think it'd be great to have a way for internal partners to see this theme demo'd with the Fluent components.

If I recall correctly, the storybook is internal only?

Azure represents a very large (largest?) business for Microsoft with a great opportunity to win the hearts and minds of thousands of Microsoft developers. Would really love to ensure they get a great experience with Fluent.

I do think keeping it in a separate package would keep things tidy, and that's good feedback about the dependency issue. We're still noodling on how to best tackle it. Open to ideas :-)

2024-03-01 03:04 UTC, AtishayMsft approved these changes

2024-03-01 19:19 UTC, fabricteam commented
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

2024-03-01 19:20 UTC, fabricteam commented
## Perf Analysis (`@fluentui/react-northstar`)
<details><summary>Perf tests with no regressions</summary>

Scenario | Current PR Ticks | Baseline Ticks | Ratio
:--- | ---:| ---:| ---:
AvatarMinimalPerf.default | [121](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/AvatarMinimalPerf.default.html) | [106](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/AvatarMinimalPerf.default_base.html) | 1.14:1
AttachmentMinimalPerf.default | [88](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/AttachmentMinimalPerf.default.html) | [78](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/AttachmentMinimalPerf.default_base.html) | 1.13:1
AccordionMinimalPerf.default | [84](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/AccordionMinimalPerf.default.html) | [75](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/AccordionMinimalPerf.default_base.html) | 1.12:1
ChatDuplicateMessagesPerf.default | [159](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ChatDuplicateMessagesPerf.default.html) | [142](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ChatDuplicateMessagesPerf.default_base.html) | 1.12:1
TreeWith60ListItems.default | [93](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/TreeWith60ListItems.default.html) | [83](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/TreeWith60ListItems.default_base.html) | 1.12:1
FlexMinimalPerf.default | [164](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/FlexMinimalPerf.default.html) | [150](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/FlexMinimalPerf.default_base.html) | 1.09:1
ChatMinimalPerf.default | [453](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ChatMinimalPerf.default.html) | [418](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ChatMinimalPerf.default_base.html) | 1.08:1
DropdownManyItemsPerf.default | [398](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/DropdownManyItemsPerf.default.html) | [373](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/DropdownManyItemsPerf.default_base.html) | 1.07:1
ProviderMinimalPerf.default | [210](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ProviderMinimalPerf.default.html) | [196](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ProviderMinimalPerf.default_base.html) | 1.07:1
RefMinimalPerf.default | [117](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/RefMinimalPerf.default.html) | [109](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/RefMinimalPerf.default_base.html) | 1.07:1
GridMinimalPerf.default | [198](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/GridMinimalPerf.default.html) | [187](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/GridMinimalPerf.default_base.html) | 1.06:1
ChatWithPopoverPerf.default | [197](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ChatWithPopoverPerf.default.html) | [188](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ChatWithPopoverPerf.default_base.html) | 1.05:1
DividerMinimalPerf.default | [203](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/DividerMinimalPerf.default.html) | [193](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/DividerMinimalPerf.default_base.html) | 1.05:1
HeaderMinimalPerf.default | [213](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/HeaderMinimalPerf.default.html) | [202](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/HeaderMinimalPerf.default_base.html) | 1.05:1
LoaderMinimalPerf.default | [194](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/LoaderMinimalPerf.default.html) | [185](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/LoaderMinimalPerf.default_base.html) | 1.05:1
TextMinimalPerf.default | [201](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/TextMinimalPerf.default.html) | [191](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/TextMinimalPerf.default_base.html) | 1.05:1
TextAreaMinimalPerf.default | [291](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/TextAreaMinimalPerf.default.html) | [277](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/TextAreaMinimalPerf.default_base.html) | 1.05:1
ButtonSlotsPerf.default | [335](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ButtonSlotsPerf.default.html) | [323](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ButtonSlotsPerf.default_base.html) | 1.04:1
HeaderSlotsPerf.default | [471](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/HeaderSlotsPerf.default.html) | [453](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/HeaderSlotsPerf.default_base.html) | 1.04:1
LayoutMinimalPerf.default | [203](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/LayoutMinimalPerf.default.html) | [195](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/LayoutMinimalPerf.default_base.html) | 1.04:1
ListMinimalPerf.default | [310](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ListMinimalPerf.default.html) | [297](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ListMinimalPerf.default_base.html) | 1.04:1
FormMinimalPerf.default | [230](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/FormMinimalPerf.default.html) | [223](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/FormMinimalPerf.default_base.html) | 1.03:1
MenuButtonMinimalPerf.default | [955](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/MenuButtonMinimalPerf.default.html) | [927](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/MenuButtonMinimalPerf.default_base.html) | 1.03:1
RosterPerf.default | [1551](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/RosterPerf.default.html) | [1509](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/RosterPerf.default_base.html) | 1.03:1
SliderMinimalPerf.default | [738](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/SliderMinimalPerf.default.html) | [714](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/SliderMinimalPerf.default_base.html) | 1.03:1
StatusMinimalPerf.default | [390](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/StatusMinimalPerf.default.html) | [380](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/StatusMinimalPerf.default_base.html) | 1.03:1
AlertMinimalPerf.default | [152](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/AlertMinimalPerf.default.html) | [149](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/AlertMinimalPerf.default_base.html) | 1.02:1
BoxMinimalPerf.default | [200](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/BoxMinimalPerf.default.html) | [197](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/BoxMinimalPerf.default_base.html) | 1.02:1
ButtonOverridesMissPerf.default | [658](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ButtonOverridesMissPerf.default.html) | [645](https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test-northstar/ButtonOverridesMis [...]

2024-03-01 19:24 UTC, fabricteam commented
## 🕵 FluentUIV0 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v0"/>

2024-03-01 19:31 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>BaseButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/BaseButton-mount_base.html">624</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/BaseButton-mount.html">628</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Breadcrumb</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/Breadcrumb-mount_base.html">1668</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/Breadcrumb-mount.html">1703</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Checkbox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/Checkbox-mount_base.html">1678</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/Checkbox-mount.html">1705</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>CheckboxBase</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/CheckboxBase-mount_base.html">1472</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/CheckboxBase-mount.html">1500</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ChoiceGroup</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/ChoiceGroup-mount_base.html">2950</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/ChoiceGroup-mount.html">2931</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>ComboBox</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/ComboBox-mount_base.html">664</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/ComboBox-mount.html">667</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>CommandBar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/CommandBar-mount_base.html">6203</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/CommandBar-mount.html">6248</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>ContextualMenu</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/ContextualMenu-mount_base.html">13324</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/ContextualMenu-mount.html">13221</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DefaultButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DefaultButton-mount_base.html">734</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DefaultButton-mount.html">731</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRow</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DetailsRow-mount_base.html">2169</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DetailsRow-mount.html">2193</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowFast</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DetailsRowFast-mount_base.html">2172</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DetailsRowFast-mount.html">2189</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>DetailsRowNoStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DetailsRowNoStyles-mount_base.html">2006</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DetailsRowNoStyles-mount.html">2016</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Dialog</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/Dialog-mount_base.html">2674</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/Dialog-mount.html">2684</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>DocumentCardTitle</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DocumentCardTitle-mount_base.html">242</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/DocumentCardTitle-mount.html">236</a></td>
            <td>1000</td>
            <td></td>
           </tr>
<tr>
            <td>Dropdown</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/Dropdown-mount_base.html">1972</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/Dropdown-mount.html">1984</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusTrapZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/FocusTrapZone-mount_base.html">1150</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/FocusTrapZone-mount.html">1148</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FocusZone</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/FocusZone-mount_base.html">1094</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/FocusZone-mount.html">1067</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/GroupedList-mount_base.html">42015</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/GroupedList-mount.html">42006</a></td>
            <td>2</td>
            <td></td>
           </tr>
<tr>
            <td>GroupedList</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/GroupedList-virtual-rerender_base.html">20201</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/30365/perf-test/GroupedList-virtual-rerender.ht [...]

2024-03-06 18:55 UTC, fabricteam commented on api-extractor.json
> +/**
## [🕵 FluentUIV0 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=30365&commitId=6210dddab7f4a717c3e1933692ef367571b26c6d&env=prod&clientType=FLUENTUI)


  <details><summary><b>Card</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Card.Card Example Focusable Teams High Contrast.chromium.png|0| Added|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v0"/>

2024-03-06 19:57 UTC, fabricteam commented on api-extractor.json
> +/**
## [🕵 fluentuiv8 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=30365&commitId=0c5fac8811f39a845ade1ff321f41f1d56bd7a7a&env=prod&clientType=FLUENTUI)


  <details><summary><b>Shimmer</b> 2 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Shimmer.Data loaded.default.chromium.png|0| Added|
|Shimmer.Data not loaded.default.chromium.png|0| Added|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

2024-03-06 20:02 UTC, fabricteam commented
## 🕵 FluentUIV0 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v0"/>

2024-03-07 00:08 UTC, fabricteam commented
## 🕵 fluentuiv8 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v8"/>

2024-04-18 20:33 UTC, closed without merging