fix: Restore focus when the focused treeitem is unmounted
microsoft/fluentui pull request #31105
Opened 2024-04-18 10:45 UTC by ling1726

fixes #30001

2024-04-18 10:45 UTC, ling1726 commented on packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
> +  const handleFocusedUnmountRef = React.useMemo(() => {
TODO; write e2e tests

2024-04-18 10:55 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)
<p>No significant results to display.</p><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/Avatar-mount_base.html">638</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/Avatar-mount.html">649</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/Button-mount_base.html">300</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/Button-mount.html">303</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/Field-mount_base.html">1136</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/Field-mount.html">1147</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/FluentProvider-mount_base.html">694</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/FluentProvider-mount.html">720</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/FluentProviderWithTheme-mount_base.html">87</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/FluentProviderWithTheme-mount.html">80</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">34</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">37</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">69</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">71</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/MakeStyles-mount_base.html">878</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/MakeStyles-mount.html">873</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/Persona-mount_base.html">1731</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/Persona-mount.html">1747</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/SpinButton-mount_base.html">1387</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/SpinButton-mount.html">1398</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/SwatchPicker-mount_base.html">1506</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31105/perf-test-react-components/SwatchPicker-mount.html">1528</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2024-04-18 10:58 UTC, fabricteam commented
## 📊 Bundle size report

✅ No changes found
<div id="bundleSizeComment9423"/>

2024-04-18 11:09 UTC, fabricteam commented
## 🕵 fluentuiv9 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

2024-04-18 11:59 UTC, bsunderhus commented on packages/react-components/react-tree/src/components/Tree/useTree.ts
> +          if (!event.defaultPrevented) {
```suggestion
          // isDefaultPrevented cannot be used here
          // as we're creating a synthetic event
          // on element unmount
          if (!event.defaultPrevented) {
```
nit: Can you add a comment here explaining why we cannot trust in `isDefaultPrevented` anymore with this change?!

2024-04-18 11:59 UTC, bsunderhus commented on packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
> +              event: createSyntheticKeyboardEvent(ArrowDown, el),
```suggestion
              event: createSyntheticKeyboardEvent(ArrowUp, el),
```

2024-04-18 12:01 UTC, bsunderhus commented on packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
> +        el = e;
If you use `useIsomorphicLayoutEffect` instead of a memoized ref you can avoid this `el` -> `e` naming problem here and just use `triggerRef` instead

2024-04-18 12:04 UTC, bsunderhus reviewed
The `TreeManupulation` story has to be updated accordingly. Before this fix, that story was doing this manually, now it's no longer required

2024-04-18 12:09 UTC, bsunderhus requested changes
Seems like this change is somehow breaking the Virtualization example, on navigation from children to parent when the parent is not visible:

![image](https://github.com/microsoft/fluentui/assets/5483269/421221a9-6ed0-49fb-b22c-b071b9bdbffd)


By the error log message I believe it might be related to how we consume the synthetic event target in the navigation

2024-04-30 15:03 UTC, closed without merging

2024-04-30 17:04 UTC, bsunderhus commented
Will follow up with https://github.com/microsoft/fluentui/pull/31231