add data support to option
microsoft/fluentui pull request #31696
Opened 2024-06-13 08:19 UTC by ymyqwe

While v8 dropdown supports passing data to the click event, v9 does not support this.

## Previous Behavior
No data is passed when option is clicked.

## New Behavior
Data is passed to then OnOptionSelect event.

## Related Issue(s)

- Fixes #

2024-06-13 12:26 UTC, layershifter requested changes
This is intentionally is not supported as this pattern leads to memoization issues.

2024-06-17 09:23 UTC, ymyqwe commented
> This is intentionally is not supported as this pattern leads to memoization issues by design. If you need to support such feature, I suggest to create a custom component.

The custom data passed to option click event is widely used in Dropdown v8 in our scenarios. 

And in my solution the props.data is optional so it will only leads to memoization issues when data is set. Would it be possible to support this feature?

2024-06-17 12:55 UTC, layershifter commented
> And in my solution the props.data is optional so it will only leads to memoization issues when data is set. Would it be possible to support this feature?

We would like to avoid patterns what cause problems by design in library, that's why this feature is not supported as I mentioned. You can create a `CustomOption` component on your side to support such additional scenarios:

```ts
const CustomOption = React.forwardRef(() => {
  const onOptionSelect = (e, data) => {
    props.onOptionSelect(e, { ...data, props.data });
  }

  return <Option {...props} onOptionSelect={onOptionSelect} />
})
```

2024-06-17 15:37 UTC, ymyqwe commented
> > And in my solution the props.data is optional so it will only leads to memoization issues when data is set. Would it be possible to support this feature?
> 
> We would like to avoid patterns what cause problems by design in library, that's why this feature is not supported as I mentioned. You can create a `CustomOption` component on your side to support such additional scenarios:
> 
> ```ts
> const CustomOption = React.forwardRef(() => {
>   const onOptionSelect = (e, data) => {
>     props.onOptionSelect(e, { ...data, props.data });
>   }
> 
>   return <Option {...props} onOptionSelect={onOptionSelect} />
> })
> ```

Make sense, I will implement this logic at our side. Thanks for the explanation. You can close the issue now.

2024-06-17 19:05 UTC, closed without merging