fix: change useComboboxFilter hook to filter by option text
microsoft/fluentui pull request #31747
Opened 2024-06-18 10:30 UTC by dmytrokirpa

## Previous Behavior

The `useComboboxFilter` hook utilizes the value, not the text, to filter options.

## New Behavior

The `useComboboxFilter` hook utilizes the text to filter options, and if it's not string-like (html element), it defaults to the option value.

## Related Issue(s)

- Fixes #31464

2024-06-18 10:40 UTC, fabricteam commented
## [Perf Analysis (`@fluentui/react-components`)](https://github.com/microsoft/fluentui/wiki/Perf-Testing)

  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">31</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">40</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.regression.txt">Possible regression</a></td>
           </tr></table><details><summary>All results</summary><p>
  <table>
  <tr>
    <th>Scenario</th>
    <th>Render type</th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">Master Ticks</a>
    </th>
    <th>
      <a href="https://github.com/microsoft/fluentui/wiki/Perf-Testing#why-are-results-listed-in-ticks-instead-of-time-units">PR Ticks</a>
    </th>
    <th>Iterations</th>
    <th>Status</th>
  </tr><tr>
            <td>Avatar</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/Avatar-mount_base.html">608</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/Avatar-mount.html">654</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Button</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/Button-mount_base.html">308</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/Button-mount.html">295</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>Field</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/Field-mount_base.html">1170</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/Field-mount.html">1152</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProvider</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProvider-mount_base.html">706</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProvider-mount.html">696</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-mount_base.html">86</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-mount.html">87</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-virtual-rerender_base.html">31</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.html">40</a></td>
            <td>10</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-virtual-rerender.regression.txt">Possible regression</a></td>
           </tr>
<tr>
            <td>FluentProviderWithTheme</td>
            <td>virtual-rerender-with-unmount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount_base.html">80</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/FluentProviderWithTheme-virtual-rerender-with-unmount.html">72</a></td>
            <td>10</td>
            <td></td>
           </tr>
<tr>
            <td>MakeStyles</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/MakeStyles-mount_base.html">855</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/MakeStyles-mount.html">882</a></td>
            <td>50000</td>
            <td></td>
           </tr>
<tr>
            <td>Persona</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/Persona-mount_base.html">1783</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/Persona-mount.html">1678</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SpinButton</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/SpinButton-mount_base.html">1350</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/SpinButton-mount.html">1400</a></td>
            <td>5000</td>
            <td></td>
           </tr>
<tr>
            <td>SwatchPicker</td>
            <td>mount</td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/SwatchPicker-mount_base.html">1632</a></td>
            <td><a href="https://fluentuipr.z22.web.core.windows.net/pull/31747/perf-test-react-components/SwatchPicker-mount.html">1681</a></td>
            <td>5000</td>
            <td></td>
           </tr></table></p></details>

<div id="perfComment9425"/>

2024-06-18 10:40 UTC, fabricteam commented
## 📊 Bundle size report

✅ No changes found
<div id="bundleSizeComment9423"/>

2024-06-18 10:57 UTC, fabricteam commented on change/@fluentui-react-combobox-8e0ae73a-c593-485c-b6f0-a5f4e576a378.json
> +{
## [🕵 fluentuiv9 Open the Visual Regressions report to inspect the affected screenshots]( https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=31747&commitId=fea48b47efd3dd5cc626b98dc8e52e9b2e0d38c4&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar Converged</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar Converged.badgeMask.normal.chromium.png|3| Changed|

</details>


  <details><summary><b>Card Converged - Interactive</b> 6 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Card Converged - Interactive.appearance interactive - Filled - High Contrast.click.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled - High Contrast.hover.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled - High Contrast.normal.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled Alternative - High Contrast.click.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled Alternative - High Contrast.hover.chromium.png|0| Added|
|Card Converged - Interactive.appearance interactive - Filled Alternative - High Contrast.normal.chromium.png|0| Added|

</details>


  <details><summary><b>SwatchPicker Converged</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|SwatchPicker Converged.Shape.default.chromium.png|0| Added|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_v9"/>

2024-06-19 15:20 UTC, JoseHerminioCollas commented
The key values are still showing up in the display.

I can use an element as a `children` in the `options` array that I will provide to the `Combobox` as the following:
```
const options = [
  { children: <em>Alligator</em>, value: '1' },
  { children: 'Bee', value: '2' },

```
The `Option` with the `EM` tag is selected:
![image](https://github.com/microsoft/fluentui/assets/11412989/c6d36cf2-a03d-4f72-9e84-c3c28bbb11ca)

![image](https://github.com/microsoft/fluentui/assets/11412989/afd709a4-b9b2-44af-8060-dcf2adb1ad02)

The value that is displayed is not the correct value
![image](https://github.com/microsoft/fluentui/assets/11412989/c7bd704c-48b8-4e98-9422-8982f4b0aebb)

The expected behavior is that the `children` value is displayed not the `value` value.

2024-06-20 09:06 UTC, dmytrokirpa commented
> The key values are still showing up in the display.
> 
> I can use an element as a `children` in the `options` array that I will provide to the `Combobox` as the following:
> 
> ```
> const options = [
>   { children: <em>Alligator</em>, value: '1' },
>   { children: 'Bee', value: '2' },
> ```
> 
> The `Option` with the `EM` tag is selected: ![image](https://private-user-images.githubusercontent.com/11412989/341125328-c6d36cf2-a03d-4f72-9e84-c3c28bbb11ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ0NzksIm5iZiI6MTcxODg3NDE3OSwicGF0aCI6Ii8xMTQxMjk4OS8zNDExMjUzMjgtYzZkMzZjZjItYTAzZC00ZjcyLTllODQtYzNjMjhiYmIxMWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZDQ3YjcxNDM2YjhkZjUxMGJiN2FmN2JmZTE2ZWNlMTViNGJjMzNlNGVkNzA1MjhjZmE3YzA4YTkzNjZmNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zb22SVYh8C5PiN-VTMLGt20cvkQt-9iZyqtAcJz7ZWM)
> 
> ![image](https://private-user-images.githubusercontent.com/11412989/341125575-afd709a4-b9b2-44af-8060-dcf2adb1ad02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ0NzksIm5iZiI6MTcxODg3NDE3OSwicGF0aCI6Ii8xMTQxMjk4OS8zNDExMjU1NzUtYWZkNzA5YTQtYjliMi00NGFmLTgwNjAtZGNmMmFkYjFhZDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTEwYjhkN2I5MTAzN2ZhMTVjNjQxNjdlNTdiMGFhNjBjOTVmMDUzODllOWEzNmIxY2U2ODNiYzFhNWExODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k2mIHTQKrPWq-3kFyTNZ5PuAraK7BoX31HWNVbEmiPo)
> 
> The value that is displayed is not the correct value ![image](https://private-user-images.githubusercontent.com/11412989/341125659-c7bd704c-48b8-4e98-9422-8982f4b0aebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ0NzksIm5iZiI6MTcxODg3NDE3OSwicGF0aCI6Ii8xMTQxMjk4OS8zNDExMjU2NTktYzdiZDcwNGMtNDhiOC00ZTk4LTk0MjItODk4MmY0YjBhZWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjIxMjJhMWQyYmNiYjFiMzJkNzhlYWQxY2RjZTFiMDA1YjIyZTQ3NmI2Y2Q1NjljNTI3NWJkZmU3OTY5YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JflNAfbKNMDPI96rjgWU1_lO5bx3BWa9uk58AbDsOlM)
> 
> The expected behavior is that the `children` value is displayed not the `value` value.

Thank you, @JoseHerminioCollas, for highlighting this issue. The challenge is that HTML elements cannot be rendered within an input field. I have implemented some logic to accommodate this use-case, although I am uncertain of its value. Let's await the team's feedback.

2024-06-20 18:52 UTC, layershifter requested changes
Any direct manipulation of children should be avoid as it leads to unpredictable hard to explain results, for example:

```tsx
function Hello() {
  return <>Hello</>;
}

expect(childrenToString(<span>Hello</span>)).toEqual('Hello'); // ✅ 
expect(childrenToString(<Hello />)).toEqual('Hello'); // 🔴  won't pass as `Hello` does not have children
```

2024-06-21 09:11 UTC, dmytrokirpa commented
> Any direct manipulation of children should be avoid as it leads to unpredictable hard to explain results, for example:
> 
> ```tsx
> function Hello() {
>   return <>Hello</>;
> }
> 
> expect(childrenToString(<span>Hello</span>)).toEqual('Hello'); // ✅ 
> expect(childrenToString(<Hello />)).toEqual('Hello'); // 🔴  won't pass as `Hello` does not have children
> ```

I concur that it may not be beneficial if it does not cover all scenarios.

@layershifter, what is your recommendation for this situation? Should we label the original issue as "won't do," or should we permit filtering by string-only children as in my original implementation [here](https://github.com/microsoft/fluentui/pull/31747/commits/75827a71ceb223c4a2de574ec4f578bc619c9622#diff-b27d23be71c760c92927df29d56390ca7c8fcaf7367369d00946623227c012caR36)?

2024-06-24 11:03 UTC, ling1726 commented
@dmytrokirpa  I don't think this feature is necessary. There is a `optionToText` function in the API that lets users determine what text is filtered on: here's an example https://stackblitz.com/edit/nhpsvt?file=src%2Fexample.tsx

2024-06-24 11:53 UTC, closed without merging