feat: add dropdown, dropdown-list, and option elements
microsoft/fluentui pull request #32853
Opened 2024-09-17 18:37 UTC by marchbox

## Previous Behavior

## New Behavior

## Related Issue(s)

- Fixes #

2024-09-17 18:43 UTC, fabricteam commented
## 📊 Bundle size report

✅ No changes found
<div id="bundleSizeComment9423"/>

2024-09-17 18:48 UTC, fabricteam commented
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-09-17 20:57 UTC, fabricteam commented on change/@fluentui-web-components-f31af4c0-c41e-4c01-9a94-901b6d35fa63.json
> +{
## 🕵🏾‍♀️ [<b data-uid='vrt-gist'></b> visual regressions to review in the fluentui-web-components-v3 Visual Regression Report](https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=32853&commitId=93cd5e55de043cd0005c03567d317ce6d04e8a19&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar.Image.chromium.png|248| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-09-17 21:08 UTC, fabricteam commented
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-09-18 18:39 UTC, fabricteam commented on change/@fluentui-web-components-f31af4c0-c41e-4c01-9a94-901b6d35fa63.json
> +{
## 🕵🏾‍♀️ [<b data-uid='vrt-gist'></b> visual regressions to review in the fluentui-web-components-v3 Visual Regression Report](https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=32853&commitId=622cf28a0bca49f148bec4f8169ae47de5f5bfdc&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar.Image.chromium.png|248| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-09-23 22:02 UTC, fabricteam commented
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-09-25 02:09 UTC, davatron5000 requested changes
Generally speaking, this is looking good. There's a lot going on but I left some comments. Let me know when you finish your last round of changes and I'll do a final review (pulling it down and looking at it).

2024-09-27 17:19 UTC, fabricteam commented on change/@fluentui-web-components-f31af4c0-c41e-4c01-9a94-901b6d35fa63.json
> +{
## 🕵🏾‍♀️ [<b data-uid='vrt-gist'></b> visual regressions to review in the fluentui-web-components-v3 Visual Regression Report](https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=32853&commitId=35dec22765c4a8d7e61d9d6b05f4dbd0eaa93166&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar.Image.chromium.png|248| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-09-28 19:58 UTC, fabricteam commented
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-09-29 20:33 UTC, fabricteam commented on change/@fluentui-web-components-f31af4c0-c41e-4c01-9a94-901b6d35fa63.json
> +{
## 🕵🏾‍♀️ [<b data-uid='vrt-gist'></b> visual regressions to review in the fluentui-web-components-v3 Visual Regression Report](https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=32853&commitId=0cb92ccc038c67b535154c4a1121c8f87048a501&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar.Image.chromium.png|248| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-09-30 17:57 UTC, fabricteam commented
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-10-01 23:39 UTC, fabricteam commented on change/@fluentui-web-components-f31af4c0-c41e-4c01-9a94-901b6d35fa63.json
> +{
## 🕵🏾‍♀️ [<b data-uid='vrt-gist'></b> visual regressions to review in the fluentui-web-components-v3 Visual Regression Report](https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=32853&commitId=25987c010b94a736dbcd71ef2796306afe92d264&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar.Image.chromium.png|248| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-10-02 19:08 UTC, fabricteam commented
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-10-04 22:59 UTC, fabricteam commented on change/@fluentui-web-components-f31af4c0-c41e-4c01-9a94-901b6d35fa63.json
> +{
## 🕵🏾‍♀️ [<b data-uid='vrt-gist'></b> visual regressions to review in the fluentui-web-components-v3 Visual Regression Report](https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-approval/index.html?organization=uifabric&project=fabricpublic&prId=32853&commitId=0d9ad27180561982f37a63ade98db663a93b48f0&env=prod&clientType=FLUENTUI)


  <details><summary><b>Avatar</b> 1 screenshots</summary>

|Image Name|Diff(in Pixels)| Image Type
|-|-|-|
|Avatar.Image.chromium.png|248| Changed|

</details>




<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-10-08 19:23 UTC, fabricteam commented
## 🕵 fluentui-web-components-v3 No visual regressions between this PR and main
<div id="vrtCommentfluent-ui_VRT_Pipeline_web-components"/>

2024-12-03 21:28 UTC, closed without merging

2024-12-03 21:28 UTC, marchbox commented
Closing this in favor of https://github.com/microsoft/fluentui/pull/32116